INSERT INTO run_access_keys (
    run_id,
    project_id,
    correlation_id,
    runtime_mode,
    namespace,
    target_env,
    key_hash,
    status,
    issued_at,
    expires_at,
    revoked_at,
    last_used_at,
    created_by,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2::uuid,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
ON CONFLICT (run_id) DO UPDATE SET
    project_id = EXCLUDED.project_id,
    correlation_id = EXCLUDED.correlation_id,
    runtime_mode = EXCLUDED.runtime_mode,
    namespace = EXCLUDED.namespace,
    target_env = EXCLUDED.target_env,
    key_hash = EXCLUDED.key_hash,
    status = EXCLUDED.status,
    issued_at = EXCLUDED.issued_at,
    expires_at = EXCLUDED.expires_at,
    revoked_at = EXCLUDED.revoked_at,
    last_used_at = EXCLUDED.last_used_at,
    created_by = EXCLUDED.created_by,
    updated_at = EXCLUDED.updated_at
RETURNING
    run_id,
    project_id::text AS project_id,
    correlation_id,
    runtime_mode,
    namespace,
    target_env,
    key_hash,
    status,
    issued_at,
    expires_at,
    revoked_at,
    last_used_at,
    created_by,
    created_at,
    updated_at;
