#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1091
source "${ROOT_DIR}/lib.sh"
load_env_file "${BOOTSTRAP_ENV_FILE:?}"

: "${CODEXK8S_GITHUB_REPO:?CODEXK8S_GITHUB_REPO is required}"
: "${CODEXK8S_GITHUB_PAT:?CODEXK8S_GITHUB_PAT is required}"
: "${CODEXK8S_OPENAI_API_KEY:=}"
: "${CODEXK8S_OPENAI_AUTH_FILE:=}"
: "${CODEXK8S_POSTGRES_PASSWORD:?CODEXK8S_POSTGRES_PASSWORD is required}"
: "${CODEXK8S_APP_SECRET_KEY:?CODEXK8S_APP_SECRET_KEY is required}"
: "${CODEXK8S_TOKEN_ENCRYPTION_KEY:?CODEXK8S_TOKEN_ENCRYPTION_KEY is required}"
: "${CODEXK8S_GITHUB_WEBHOOK_SECRET:?CODEXK8S_GITHUB_WEBHOOK_SECRET is required}"
: "${CODEXK8S_STAGING_DOMAIN:?CODEXK8S_STAGING_DOMAIN is required}"
: "${CODEXK8S_PUBLIC_BASE_URL:?CODEXK8S_PUBLIC_BASE_URL is required}"
: "${CODEXK8S_BOOTSTRAP_OWNER_EMAIL:?CODEXK8S_BOOTSTRAP_OWNER_EMAIL is required}"
: "${CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS:=}"
: "${CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS:=}"
: "${CODEXK8S_GITHUB_OAUTH_CLIENT_ID:?CODEXK8S_GITHUB_OAUTH_CLIENT_ID is required}"
: "${CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET:?CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET is required}"
: "${CODEXK8S_JWT_SIGNING_KEY:?CODEXK8S_JWT_SIGNING_KEY is required}"

PLATFORM_REPO="${CODEXK8S_GITHUB_REPO}"
CODEXK8S_FIRST_PROJECT_GITHUB_REPO="${CODEXK8S_FIRST_PROJECT_GITHUB_REPO:-}"
if [ -z "${CODEXK8S_FIRST_PROJECT_GITHUB_REPO}" ]; then
  CODEXK8S_FIRST_PROJECT_GITHUB_REPO="${PLATFORM_REPO}"
fi
PROJECT_REPO="${CODEXK8S_FIRST_PROJECT_GITHUB_REPO}"

CODEXK8S_STAGING_NAMESPACE="${CODEXK8S_STAGING_NAMESPACE:-codex-k8s-ai-staging}"
CODEXK8S_INTERNAL_REGISTRY_SERVICE="${CODEXK8S_INTERNAL_REGISTRY_SERVICE:-codex-k8s-registry}"
CODEXK8S_INTERNAL_REGISTRY_PORT="${CODEXK8S_INTERNAL_REGISTRY_PORT:-5000}"
CODEXK8S_INTERNAL_REGISTRY_STORAGE_SIZE="${CODEXK8S_INTERNAL_REGISTRY_STORAGE_SIZE:-20Gi}"
CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/web-console}"
CODEXK8S_INTERNAL_REGISTRY_HOST="${CODEXK8S_INTERNAL_REGISTRY_HOST:-127.0.0.1:${CODEXK8S_INTERNAL_REGISTRY_PORT}}"
CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/api-gateway}"
CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/control-plane}"
CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/worker}"
CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/agent-runner}"
CODEXK8S_API_GATEWAY_IMAGE="${CODEXK8S_API_GATEWAY_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_CONTROL_PLANE_IMAGE="${CODEXK8S_CONTROL_PLANE_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_WORKER_IMAGE="${CODEXK8S_WORKER_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_AGENT_RUNNER_IMAGE="${CODEXK8S_AGENT_RUNNER_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_WEB_CONSOLE_IMAGE="${CODEXK8S_WEB_CONSOLE_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_CONTROL_PLANE_GRPC_TARGET="${CODEXK8S_CONTROL_PLANE_GRPC_TARGET:-codex-k8s-control-plane.${CODEXK8S_STAGING_NAMESPACE}.svc.cluster.local:9090}"
CODEXK8S_CONTROL_PLANE_MCP_BASE_URL="${CODEXK8S_CONTROL_PLANE_MCP_BASE_URL:-}"
CODEXK8S_WAIT_ROLLOUT="${CODEXK8S_WAIT_ROLLOUT:-true}"
CODEXK8S_ROLLOUT_TIMEOUT="${CODEXK8S_ROLLOUT_TIMEOUT:-1800s}"
CODEXK8S_RUNNER_SCALE_SET_NAME="${CODEXK8S_RUNNER_SCALE_SET_NAME:-codex-k8s-ai-staging}"
CODEXK8S_LEARNING_MODE_DEFAULT="${CODEXK8S_LEARNING_MODE_DEFAULT:-}"
CODEXK8S_KANIKO_TIMEOUT="${CODEXK8S_KANIKO_TIMEOUT:-1800s}"
CODEXK8S_KANIKO_CACHE_ENABLED="${CODEXK8S_KANIKO_CACHE_ENABLED:-true}"
CODEXK8S_KANIKO_CACHE_REPO="${CODEXK8S_KANIKO_CACHE_REPO:-}"
CODEXK8S_KANIKO_CACHE_TTL="${CODEXK8S_KANIKO_CACHE_TTL:-168h}"
CODEXK8S_KANIKO_CACHE_COMPRESSED="${CODEXK8S_KANIKO_CACHE_COMPRESSED:-false}"
CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL="${CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL:-4}"
CODEXK8S_GITHUB_WEBHOOK_URL="${CODEXK8S_GITHUB_WEBHOOK_URL:-https://${CODEXK8S_STAGING_DOMAIN}/api/v1/webhooks/github}"
CODEXK8S_GITHUB_WEBHOOK_EVENTS="${CODEXK8S_GITHUB_WEBHOOK_EVENTS:-}"
CODEXK8S_WORKER_REPLICAS="${CODEXK8S_WORKER_REPLICAS:-1}"
CODEXK8S_WORKER_POLL_INTERVAL="${CODEXK8S_WORKER_POLL_INTERVAL:-}"
CODEXK8S_WORKER_CLAIM_LIMIT="${CODEXK8S_WORKER_CLAIM_LIMIT:-}"
CODEXK8S_WORKER_RUNNING_CHECK_LIMIT="${CODEXK8S_WORKER_RUNNING_CHECK_LIMIT:-}"
CODEXK8S_WORKER_SLOTS_PER_PROJECT="${CODEXK8S_WORKER_SLOTS_PER_PROJECT:-}"
CODEXK8S_WORKER_SLOT_LEASE_TTL="${CODEXK8S_WORKER_SLOT_LEASE_TTL:-}"
CODEXK8S_WORKER_K8S_NAMESPACE="${CODEXK8S_WORKER_K8S_NAMESPACE:-}"
CODEXK8S_WORKER_JOB_IMAGE="${CODEXK8S_WORKER_JOB_IMAGE:-}"
CODEXK8S_WORKER_JOB_COMMAND="${CODEXK8S_WORKER_JOB_COMMAND:-}"
CODEXK8S_WORKER_JOB_TTL_SECONDS="${CODEXK8S_WORKER_JOB_TTL_SECONDS:-}"
CODEXK8S_WORKER_JOB_BACKOFF_LIMIT="${CODEXK8S_WORKER_JOB_BACKOFF_LIMIT:-}"
CODEXK8S_WORKER_JOB_ACTIVE_DEADLINE_SECONDS="${CODEXK8S_WORKER_JOB_ACTIVE_DEADLINE_SECONDS:-}"
CODEXK8S_WORKER_RUN_NAMESPACE_PREFIX="${CODEXK8S_WORKER_RUN_NAMESPACE_PREFIX:-}"
CODEXK8S_WORKER_RUN_NAMESPACE_CLEANUP="${CODEXK8S_WORKER_RUN_NAMESPACE_CLEANUP:-}"
CODEXK8S_WORKER_RUN_SERVICE_ACCOUNT="${CODEXK8S_WORKER_RUN_SERVICE_ACCOUNT:-}"
CODEXK8S_WORKER_RUN_ROLE_NAME="${CODEXK8S_WORKER_RUN_ROLE_NAME:-}"
CODEXK8S_WORKER_RUN_ROLE_BINDING_NAME="${CODEXK8S_WORKER_RUN_ROLE_BINDING_NAME:-}"
CODEXK8S_WORKER_RUN_RESOURCE_QUOTA_NAME="${CODEXK8S_WORKER_RUN_RESOURCE_QUOTA_NAME:-}"
CODEXK8S_WORKER_RUN_LIMIT_RANGE_NAME="${CODEXK8S_WORKER_RUN_LIMIT_RANGE_NAME:-}"
CODEXK8S_WORKER_RUN_CREDENTIALS_SECRET_NAME="${CODEXK8S_WORKER_RUN_CREDENTIALS_SECRET_NAME:-}"
CODEXK8S_WORKER_RUN_QUOTA_PODS="${CODEXK8S_WORKER_RUN_QUOTA_PODS:-}"
if [ -z "${CODEXK8S_AGENT_DEFAULT_MODEL:-}" ]; then
  if [ -n "${CODEXK8S_OPENAI_AUTH_FILE}" ]; then
    CODEXK8S_AGENT_DEFAULT_MODEL="gpt-5.3-codex"
  else
    CODEXK8S_AGENT_DEFAULT_MODEL="gpt-5.2-codex"
  fi
fi
CODEXK8S_AGENT_DEFAULT_REASONING_EFFORT="${CODEXK8S_AGENT_DEFAULT_REASONING_EFFORT:-}"
CODEXK8S_AGENT_DEFAULT_LOCALE="${CODEXK8S_AGENT_DEFAULT_LOCALE:-}"
CODEXK8S_AGENT_BASE_BRANCH="${CODEXK8S_AGENT_BASE_BRANCH:-}"
CODEXK8S_JWT_TTL="${CODEXK8S_JWT_TTL:-}"
CODEXK8S_MCP_TOKEN_TTL="${CODEXK8S_MCP_TOKEN_TTL:-}"
CODEXK8S_MCP_TOKEN_SIGNING_KEY="${CODEXK8S_MCP_TOKEN_SIGNING_KEY:-}"
CODEXK8S_GIT_BOT_USERNAME="${CODEXK8S_GIT_BOT_USERNAME:-}"
CODEXK8S_GIT_BOT_MAIL="${CODEXK8S_GIT_BOT_MAIL:-}"
CODEXK8S_GIT_BOT_TOKEN="${CODEXK8S_GIT_BOT_TOKEN:-}"
CODEXK8S_PROJECT_DB_ADMIN_HOST="${CODEXK8S_PROJECT_DB_ADMIN_HOST:-}"
CODEXK8S_PROJECT_DB_ADMIN_PORT="${CODEXK8S_PROJECT_DB_ADMIN_PORT:-}"
CODEXK8S_PROJECT_DB_ADMIN_USER="${CODEXK8S_PROJECT_DB_ADMIN_USER:-}"
CODEXK8S_PROJECT_DB_ADMIN_PASSWORD="${CODEXK8S_PROJECT_DB_ADMIN_PASSWORD:-}"
CODEXK8S_PROJECT_DB_ADMIN_SSLMODE="${CODEXK8S_PROJECT_DB_ADMIN_SSLMODE:-}"
CODEXK8S_PROJECT_DB_ADMIN_DATABASE="${CODEXK8S_PROJECT_DB_ADMIN_DATABASE:-}"
CODEXK8S_PROJECT_DB_LIFECYCLE_ALLOWED_ENVS="${CODEXK8S_PROJECT_DB_LIFECYCLE_ALLOWED_ENVS:-}"
CODEXK8S_K8S_API_CIDR="${CODEXK8S_K8S_API_CIDR:-0.0.0.0/0}"
CODEXK8S_K8S_API_PORT="${CODEXK8S_K8S_API_PORT:-6443}"
[ -n "${CODEXK8S_GIT_BOT_TOKEN}" ] || die "CODEXK8S_GIT_BOT_TOKEN is required"
if [ -z "${CODEXK8S_OPENAI_API_KEY}" ] && [ -z "${CODEXK8S_OPENAI_AUTH_FILE}" ]; then
  die "Either CODEXK8S_OPENAI_API_KEY or CODEXK8S_OPENAI_AUTH_FILE is required"
fi

CODEXK8S_PROJECT_DB_ADMIN_HOST="${CODEXK8S_PROJECT_DB_ADMIN_HOST:-postgres}"
CODEXK8S_PROJECT_DB_ADMIN_PORT="${CODEXK8S_PROJECT_DB_ADMIN_PORT:-}"
CODEXK8S_PROJECT_DB_ADMIN_USER="${CODEXK8S_PROJECT_DB_ADMIN_USER:-${CODEXK8S_POSTGRES_USER:-codex_k8s}}"
CODEXK8S_PROJECT_DB_ADMIN_PASSWORD="${CODEXK8S_PROJECT_DB_ADMIN_PASSWORD:-$CODEXK8S_POSTGRES_PASSWORD}"
CODEXK8S_PROJECT_DB_ADMIN_SSLMODE="${CODEXK8S_PROJECT_DB_ADMIN_SSLMODE:-}"
CODEXK8S_PROJECT_DB_ADMIN_DATABASE="${CODEXK8S_PROJECT_DB_ADMIN_DATABASE:-}"
[ -n "${CODEXK8S_PROJECT_DB_ADMIN_HOST}" ] || die "CODEXK8S_PROJECT_DB_ADMIN_HOST is required"
[ -n "${CODEXK8S_PROJECT_DB_ADMIN_USER}" ] || die "CODEXK8S_PROJECT_DB_ADMIN_USER is required"
[ -n "${CODEXK8S_PROJECT_DB_ADMIN_PASSWORD}" ] || die "CODEXK8S_PROJECT_DB_ADMIN_PASSWORD is required"

log "Configure platform GitHub repository variables/secrets for ${PLATFORM_REPO}"
if [ "${PROJECT_REPO}" = "${PLATFORM_REPO}" ]; then
  log "Configure webhook/labels in platform repository ${PLATFORM_REPO} (dogfooding mode)"
else
  log "Configure webhook/labels in repositories: platform=${PLATFORM_REPO}, first-project=${PROJECT_REPO}"
fi
printf %s "${CODEXK8S_GITHUB_PAT}" | gh auth login --with-token

WEBHOOK_LABEL_REPOS=("${PLATFORM_REPO}")
if [ "${PROJECT_REPO}" != "${PLATFORM_REPO}" ]; then
  WEBHOOK_LABEL_REPOS+=("${PROJECT_REPO}")
fi

set_repo_var() {
  local key="$1"
  local default_value="$2"
  local value="${!key:-$default_value}"
  if [ -n "${value}" ]; then
    gh variable set "${key}" -R "${PLATFORM_REPO}" --body "${value}"
    return 0
  fi
  gh variable delete "${key}" -R "${PLATFORM_REPO}" >/dev/null 2>&1 || true
}

get_repo_var() {
  local key="$1"
  local default_value="$2"
  printf '%s' "${!key:-$default_value}"
}

ensure_repo_label() {
  local repo="$1"
  local name="$2"
  local description="$3"
  [ -n "$name" ] || return 0

  if gh label view "$name" -R "${repo}" >/dev/null 2>&1; then
    gh label edit "$name" -R "${repo}" --description "$description" >/dev/null
    return 0
  fi

  gh label create "$name" -R "${repo}" --description "$description" >/dev/null
}

configure_repo_webhook() {
  local repo="$1"
  log "Configure GitHub repository webhook for ${repo}: ${CODEXK8S_GITHUB_WEBHOOK_URL}"

  local hook_id=""
  hook_id="$(
    gh api "repos/${repo}/hooks" \
      --jq ".[] | select(.config.url == \"${CODEXK8S_GITHUB_WEBHOOK_URL}\") | .id" \
      | head -n1 || true
  )"

  local -a webhook_events=()
  IFS=',' read -r -a webhook_events <<< "${CODEXK8S_GITHUB_WEBHOOK_EVENTS}"

  local -a webhook_api_args=(
    -f "config[url]=${CODEXK8S_GITHUB_WEBHOOK_URL}"
    -f "config[content_type]=json"
    -f "config[insecure_ssl]=0"
    -f "config[secret]=${CODEXK8S_GITHUB_WEBHOOK_SECRET}"
    -F "active=true"
  )

  local event trimmed
  for event in "${webhook_events[@]}"; do
    trimmed="$(printf '%s' "$event" | xargs)"
    [ -n "$trimmed" ] || continue
    webhook_api_args+=(-f "events[]=${trimmed}")
  done

  if [ -n "${hook_id}" ]; then
    gh api "repos/${repo}/hooks/${hook_id}" -X PATCH "${webhook_api_args[@]}" >/dev/null
    log "Updated webhook id=${hook_id} in ${repo}"
  else
    gh api "repos/${repo}/hooks" -X POST -f "name=web" "${webhook_api_args[@]}" >/dev/null
    log "Created webhook for ${CODEXK8S_GITHUB_WEBHOOK_URL} in ${repo}"
  fi
}

# Variables used by staging deploy workflow.
gh variable set CODEXK8S_STAGING_NAMESPACE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_STAGING_NAMESPACE}"
gh variable set CODEXK8S_INTERNAL_REGISTRY_SERVICE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_INTERNAL_REGISTRY_SERVICE}"
gh variable set CODEXK8S_INTERNAL_REGISTRY_PORT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_INTERNAL_REGISTRY_PORT}"
gh variable set CODEXK8S_INTERNAL_REGISTRY_STORAGE_SIZE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_INTERNAL_REGISTRY_STORAGE_SIZE}"
gh variable set CODEXK8S_INTERNAL_REGISTRY_HOST -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_INTERNAL_REGISTRY_HOST}"
gh variable set CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY}"
gh variable set CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY}"
gh variable set CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY}"
gh variable set CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY}"
gh variable set CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY}"
gh variable set CODEXK8S_KANIKO_TIMEOUT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_KANIKO_TIMEOUT}"
gh variable set CODEXK8S_KANIKO_CACHE_ENABLED -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_KANIKO_CACHE_ENABLED}"
gh variable set CODEXK8S_KANIKO_CACHE_REPO -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_KANIKO_CACHE_REPO}"
gh variable set CODEXK8S_KANIKO_CACHE_TTL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_KANIKO_CACHE_TTL}"
gh variable set CODEXK8S_KANIKO_CACHE_COMPRESSED -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_KANIKO_CACHE_COMPRESSED}"
gh variable set CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL}"
gh variable set CODEXK8S_API_GATEWAY_IMAGE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_API_GATEWAY_IMAGE}"
gh variable set CODEXK8S_CONTROL_PLANE_IMAGE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_CONTROL_PLANE_IMAGE}"
gh variable set CODEXK8S_WORKER_IMAGE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_IMAGE}"
gh variable set CODEXK8S_AGENT_RUNNER_IMAGE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_AGENT_RUNNER_IMAGE}"
gh variable set CODEXK8S_WEB_CONSOLE_IMAGE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WEB_CONSOLE_IMAGE}"
gh variable set CODEXK8S_K8S_API_CIDR -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_K8S_API_CIDR}"
gh variable set CODEXK8S_K8S_API_PORT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_K8S_API_PORT}"
gh variable set CODEXK8S_WAIT_ROLLOUT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WAIT_ROLLOUT}"
gh variable set CODEXK8S_ROLLOUT_TIMEOUT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_ROLLOUT_TIMEOUT}"
gh variable set CODEXK8S_STAGING_RUNNER -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_RUNNER_SCALE_SET_NAME}"
gh variable set CODEXK8S_WORKER_REPLICAS -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_REPLICAS}"
gh variable set CODEXK8S_WORKER_POLL_INTERVAL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_POLL_INTERVAL}"
gh variable set CODEXK8S_WORKER_CLAIM_LIMIT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_CLAIM_LIMIT}"
gh variable set CODEXK8S_WORKER_RUNNING_CHECK_LIMIT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUNNING_CHECK_LIMIT}"
gh variable set CODEXK8S_WORKER_SLOTS_PER_PROJECT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_SLOTS_PER_PROJECT}"
gh variable set CODEXK8S_WORKER_SLOT_LEASE_TTL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_SLOT_LEASE_TTL}"
gh variable set CODEXK8S_WORKER_K8S_NAMESPACE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_K8S_NAMESPACE}"
gh variable set CODEXK8S_WORKER_JOB_IMAGE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_JOB_IMAGE}"
gh variable set CODEXK8S_WORKER_JOB_COMMAND -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_JOB_COMMAND}"
gh variable set CODEXK8S_WORKER_JOB_TTL_SECONDS -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_JOB_TTL_SECONDS}"
gh variable set CODEXK8S_WORKER_JOB_BACKOFF_LIMIT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_JOB_BACKOFF_LIMIT}"
gh variable set CODEXK8S_WORKER_JOB_ACTIVE_DEADLINE_SECONDS -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_JOB_ACTIVE_DEADLINE_SECONDS}"
gh variable set CODEXK8S_WORKER_RUN_NAMESPACE_PREFIX -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_NAMESPACE_PREFIX}"
gh variable set CODEXK8S_WORKER_RUN_NAMESPACE_CLEANUP -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_NAMESPACE_CLEANUP}"
gh variable set CODEXK8S_WORKER_RUN_SERVICE_ACCOUNT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_SERVICE_ACCOUNT}"
gh variable set CODEXK8S_WORKER_RUN_ROLE_NAME -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_ROLE_NAME}"
gh variable set CODEXK8S_WORKER_RUN_ROLE_BINDING_NAME -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_ROLE_BINDING_NAME}"
gh variable set CODEXK8S_WORKER_RUN_RESOURCE_QUOTA_NAME -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_RESOURCE_QUOTA_NAME}"
gh variable set CODEXK8S_WORKER_RUN_LIMIT_RANGE_NAME -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_LIMIT_RANGE_NAME}"
gh variable set CODEXK8S_WORKER_RUN_CREDENTIALS_SECRET_NAME -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_CREDENTIALS_SECRET_NAME}"
gh variable set CODEXK8S_WORKER_RUN_QUOTA_PODS -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_QUOTA_PODS}"
gh variable set CODEXK8S_AGENT_DEFAULT_MODEL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_AGENT_DEFAULT_MODEL}"
gh variable set CODEXK8S_AGENT_DEFAULT_REASONING_EFFORT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_AGENT_DEFAULT_REASONING_EFFORT}"
gh variable set CODEXK8S_AGENT_DEFAULT_LOCALE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_AGENT_DEFAULT_LOCALE}"
gh variable set CODEXK8S_AGENT_BASE_BRANCH -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_AGENT_BASE_BRANCH}"
gh variable set CODEXK8S_CONTROL_PLANE_GRPC_TARGET -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_CONTROL_PLANE_GRPC_TARGET}"
gh variable set CODEXK8S_GIT_BOT_USERNAME -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GIT_BOT_USERNAME}"
gh variable set CODEXK8S_GIT_BOT_MAIL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GIT_BOT_MAIL}"
gh variable set CODEXK8S_CONTROL_PLANE_MCP_BASE_URL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_CONTROL_PLANE_MCP_BASE_URL}"
if [ -n "${CODEXK8S_LEARNING_MODE_DEFAULT}" ]; then
  gh variable set CODEXK8S_LEARNING_MODE_DEFAULT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_LEARNING_MODE_DEFAULT}"
else
  gh variable delete CODEXK8S_LEARNING_MODE_DEFAULT -R "${CODEXK8S_GITHUB_REPO}" >/dev/null 2>&1 || true
fi
gh variable set CODEXK8S_GITHUB_WEBHOOK_URL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GITHUB_WEBHOOK_URL}"
gh variable set CODEXK8S_GITHUB_WEBHOOK_EVENTS -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GITHUB_WEBHOOK_EVENTS}"
set_repo_var CODEXK8S_RUN_INTAKE_LABEL ""
set_repo_var CODEXK8S_RUN_INTAKE_REVISE_LABEL ""
set_repo_var CODEXK8S_RUN_VISION_LABEL ""
set_repo_var CODEXK8S_RUN_VISION_REVISE_LABEL ""
set_repo_var CODEXK8S_RUN_PRD_LABEL ""
set_repo_var CODEXK8S_RUN_PRD_REVISE_LABEL ""
set_repo_var CODEXK8S_RUN_ARCH_LABEL ""
set_repo_var CODEXK8S_RUN_ARCH_REVISE_LABEL ""
set_repo_var CODEXK8S_RUN_DESIGN_LABEL ""
set_repo_var CODEXK8S_RUN_DESIGN_REVISE_LABEL ""
set_repo_var CODEXK8S_RUN_PLAN_LABEL ""
set_repo_var CODEXK8S_RUN_PLAN_REVISE_LABEL ""
set_repo_var CODEXK8S_RUN_DEV_LABEL ""
set_repo_var CODEXK8S_RUN_DEV_REVISE_LABEL ""
set_repo_var CODEXK8S_RUN_DEBUG_LABEL ""
set_repo_var CODEXK8S_RUN_DOC_AUDIT_LABEL ""
set_repo_var CODEXK8S_RUN_QA_LABEL ""
set_repo_var CODEXK8S_RUN_RELEASE_LABEL ""
set_repo_var CODEXK8S_RUN_POSTDEPLOY_LABEL ""
set_repo_var CODEXK8S_RUN_OPS_LABEL ""
set_repo_var CODEXK8S_RUN_SELF_IMPROVE_LABEL ""
set_repo_var CODEXK8S_RUN_RETHINK_LABEL ""
set_repo_var CODEXK8S_MODE_DISCUSSION_LABEL "mode:discussion"
set_repo_var CODEXK8S_STATE_BLOCKED_LABEL "state:blocked"
set_repo_var CODEXK8S_STATE_IN_REVIEW_LABEL ""
set_repo_var CODEXK8S_STATE_APPROVED_LABEL "state:approved"
set_repo_var CODEXK8S_STATE_SUPERSEDED_LABEL "state:superseded"
set_repo_var CODEXK8S_STATE_ABANDONED_LABEL "state:abandoned"
set_repo_var CODEXK8S_NEED_INPUT_LABEL "need:input"
set_repo_var CODEXK8S_NEED_PM_LABEL "need:pm"
set_repo_var CODEXK8S_NEED_SA_LABEL "need:sa"
set_repo_var CODEXK8S_NEED_QA_LABEL "need:qa"
set_repo_var CODEXK8S_NEED_SRE_LABEL "need:sre"
set_repo_var CODEXK8S_NEED_EM_LABEL "need:em"
set_repo_var CODEXK8S_NEED_KM_LABEL "need:km"
set_repo_var CODEXK8S_NEED_REVIEWER_LABEL "need:reviewer"
set_repo_var CODEXK8S_AI_MODEL_GPT_5_3_CODEX_LABEL ""
set_repo_var CODEXK8S_AI_MODEL_GPT_5_3_CODEX_SPARK_LABEL ""
set_repo_var CODEXK8S_AI_MODEL_GPT_5_2_CODEX_LABEL ""
set_repo_var CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MAX_LABEL ""
set_repo_var CODEXK8S_AI_MODEL_GPT_5_2_LABEL ""
set_repo_var CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MINI_LABEL ""
set_repo_var CODEXK8S_AI_REASONING_LOW_LABEL ""
set_repo_var CODEXK8S_AI_REASONING_MEDIUM_LABEL ""
set_repo_var CODEXK8S_AI_REASONING_HIGH_LABEL ""
set_repo_var CODEXK8S_AI_REASONING_EXTRA_HIGH_LABEL ""

# Ensure label catalog exists in repositories (color is intentionally omitted;
# GitHub assigns one automatically if not provided).
for TARGET_REPO in "${WEBHOOK_LABEL_REPOS[@]}"; do
  log "Ensure label catalog in ${TARGET_REPO}"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_INTAKE_LABEL "")" "Start intake stage run"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_INTAKE_REVISE_LABEL "")" "Request intake stage revision"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_VISION_LABEL "")" "Start vision stage run"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_VISION_REVISE_LABEL "")" "Request vision stage revision"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_PRD_LABEL "")" "Start PRD stage run"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_PRD_REVISE_LABEL "")" "Request PRD stage revision"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_ARCH_LABEL "")" "Start architecture stage run"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_ARCH_REVISE_LABEL "")" "Request architecture stage revision"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_DESIGN_LABEL "")" "Start design stage run"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_DESIGN_REVISE_LABEL "")" "Request design stage revision"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_PLAN_LABEL "")" "Start planning stage run"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_PLAN_REVISE_LABEL "")" "Request planning stage revision"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_DEV_LABEL "")" "Start development run"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_DEV_REVISE_LABEL "")" "Request development revision"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_DEBUG_LABEL "")" "Retain run namespace for debugging (skip auto cleanup)"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_DOC_AUDIT_LABEL "")" "Start documentation audit run"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_QA_LABEL "")" "Start QA run"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_RELEASE_LABEL "")" "Start release run"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_POSTDEPLOY_LABEL "")" "Start post-deploy checks run"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_OPS_LABEL "")" "Start operations run"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_SELF_IMPROVE_LABEL "")" "Start self-improve run"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_RUN_RETHINK_LABEL "")" "Reopen problem framing and scope"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_MODE_DISCUSSION_LABEL "mode:discussion")" "Discussion mode: brainstorm without commit/push/PR"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_STATE_BLOCKED_LABEL "state:blocked")" "Issue is blocked"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_STATE_IN_REVIEW_LABEL "")" "Work is in review"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_STATE_APPROVED_LABEL "state:approved")" "Work is approved"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_STATE_SUPERSEDED_LABEL "state:superseded")" "Issue superseded by newer scope"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_STATE_ABANDONED_LABEL "state:abandoned")" "Issue intentionally abandoned"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_NEED_INPUT_LABEL "need:input")" "Need additional input"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_NEED_PM_LABEL "need:pm")" "Need product management input"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_NEED_SA_LABEL "need:sa")" "Need solution architecture input"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_NEED_QA_LABEL "need:qa")" "Need QA input"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_NEED_SRE_LABEL "need:sre")" "Need SRE input"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_NEED_EM_LABEL "need:em")" "Need engineering manager review"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_NEED_KM_LABEL "need:km")" "Need documentation and traceability review"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_NEED_REVIEWER_LABEL "need:reviewer")" "Need pre-review from technical reviewer"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_AI_MODEL_GPT_5_3_CODEX_LABEL "")" "Run config: model gpt-5.3-codex"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_AI_MODEL_GPT_5_3_CODEX_SPARK_LABEL "")" "Run config: model gpt-5.3-codex-spark"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_AI_MODEL_GPT_5_2_CODEX_LABEL "")" "Run config: model gpt-5.2-codex"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MAX_LABEL "")" "Run config: model gpt-5.1-codex-max"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_AI_MODEL_GPT_5_2_LABEL "")" "Run config: model gpt-5.2"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MINI_LABEL "")" "Run config: model gpt-5.1-codex-mini"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_AI_REASONING_LOW_LABEL "")" "Run config: reasoning low"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_AI_REASONING_MEDIUM_LABEL "")" "Run config: reasoning medium"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_AI_REASONING_HIGH_LABEL "")" "Run config: reasoning high"
  ensure_repo_label "${TARGET_REPO}" "$(get_repo_var CODEXK8S_AI_REASONING_EXTRA_HIGH_LABEL "")" "Run config: reasoning extra high"
done
gh variable set CODEXK8S_STAGING_DOMAIN -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_STAGING_DOMAIN}"
gh variable set CODEXK8S_PUBLIC_BASE_URL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_PUBLIC_BASE_URL}"
gh variable set CODEXK8S_BOOTSTRAP_OWNER_EMAIL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_BOOTSTRAP_OWNER_EMAIL}"
if [ -n "${CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS}" ]; then
  gh variable set CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS}"
else
  gh variable delete CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS -R "${CODEXK8S_GITHUB_REPO}" >/dev/null 2>&1 || true
fi
if [ -n "${CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS}" ]; then
  gh variable set CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS}"
else
  gh variable delete CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS -R "${CODEXK8S_GITHUB_REPO}" >/dev/null 2>&1 || true
fi
gh variable set CODEXK8S_GITHUB_OAUTH_CLIENT_ID -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GITHUB_OAUTH_CLIENT_ID}"
gh variable set CODEXK8S_JWT_TTL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_JWT_TTL}"
gh variable set CODEXK8S_MCP_TOKEN_TTL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_MCP_TOKEN_TTL}"
if [ -n "${CODEXK8S_POSTGRES_DB:-}" ]; then
  gh variable set CODEXK8S_POSTGRES_DB -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_POSTGRES_DB}"
fi
if [ -n "${CODEXK8S_POSTGRES_USER:-}" ]; then
  gh variable set CODEXK8S_POSTGRES_USER -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_POSTGRES_USER}"
fi

# Secrets used by staging deploy workflow.
if [ -n "${CODEXK8S_OPENAI_API_KEY}" ]; then
  gh secret set CODEXK8S_OPENAI_API_KEY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_OPENAI_API_KEY}"
else
  log "Skip CODEXK8S_OPENAI_API_KEY update: empty value in bootstrap env (existing GitHub secret is kept)"
fi
if [ -n "${CODEXK8S_OPENAI_AUTH_FILE}" ]; then
  gh secret set CODEXK8S_OPENAI_AUTH_FILE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_OPENAI_AUTH_FILE}"
else
  log "Skip CODEXK8S_OPENAI_AUTH_FILE update: empty value in bootstrap env (existing GitHub secret is kept)"
fi
gh secret set CODEXK8S_POSTGRES_PASSWORD -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_POSTGRES_PASSWORD}"
gh secret set CODEXK8S_APP_SECRET_KEY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_APP_SECRET_KEY}"
gh secret set CODEXK8S_TOKEN_ENCRYPTION_KEY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_TOKEN_ENCRYPTION_KEY}"
gh secret set CODEXK8S_GITHUB_WEBHOOK_SECRET -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GITHUB_WEBHOOK_SECRET}"
gh secret set CODEXK8S_GITHUB_PAT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GITHUB_PAT}"
gh secret set CODEXK8S_GIT_BOT_TOKEN -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GIT_BOT_TOKEN}"
gh secret set CODEXK8S_PROJECT_DB_ADMIN_HOST -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_PROJECT_DB_ADMIN_HOST}"
gh secret set CODEXK8S_PROJECT_DB_ADMIN_PORT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_PROJECT_DB_ADMIN_PORT}"
gh secret set CODEXK8S_PROJECT_DB_ADMIN_USER -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_PROJECT_DB_ADMIN_USER}"
gh secret set CODEXK8S_PROJECT_DB_ADMIN_PASSWORD -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_PROJECT_DB_ADMIN_PASSWORD}"
gh secret set CODEXK8S_PROJECT_DB_ADMIN_SSLMODE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_PROJECT_DB_ADMIN_SSLMODE}"
gh secret set CODEXK8S_PROJECT_DB_ADMIN_DATABASE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_PROJECT_DB_ADMIN_DATABASE}"
gh secret set CODEXK8S_PROJECT_DB_LIFECYCLE_ALLOWED_ENVS -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_PROJECT_DB_LIFECYCLE_ALLOWED_ENVS}"
gh secret set CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET}"
gh secret set CODEXK8S_JWT_SIGNING_KEY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_JWT_SIGNING_KEY}"
if [ -n "${CODEXK8S_MCP_TOKEN_SIGNING_KEY}" ]; then
  gh secret set CODEXK8S_MCP_TOKEN_SIGNING_KEY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_MCP_TOKEN_SIGNING_KEY}"
else
  gh secret delete CODEXK8S_MCP_TOKEN_SIGNING_KEY -R "${CODEXK8S_GITHUB_REPO}" >/dev/null 2>&1 || true
fi
if [ -n "${CODEXK8S_CONTEXT7_API_KEY:-}" ]; then
  gh secret set CODEXK8S_CONTEXT7_API_KEY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_CONTEXT7_API_KEY}"
fi

# Cleanup legacy non-prefixed names to keep a single naming convention.
for legacy_secret in OPENAI_API_KEY CONTEXT7_API_KEY; do
  gh secret delete "${legacy_secret}" -R "${CODEXK8S_GITHUB_REPO}" >/dev/null 2>&1 || true
done
for legacy_secret in CODEXK8S_GITHUB_TOKEN CODEXK8S_GITHUB_USERNAME; do
  gh secret delete "${legacy_secret}" -R "${CODEXK8S_GITHUB_REPO}" >/dev/null 2>&1 || true
done
for legacy_var in STAGING_NAMESPACE STAGING_DOMAIN POSTGRES_DB POSTGRES_USER LEARNING_MODE_DEFAULT RUNNER_NAMESPACE RUNNER_SCALE_SET_NAME RUNNER_MIN RUNNER_MAX RUNNER_IMAGE CODEXK8S_GITHUB_USERNAME CODEXK8S_IMAGE CODEXK8S_INTERNAL_IMAGE_REPOSITORY; do
  gh variable delete "${legacy_var}" -R "${CODEXK8S_GITHUB_REPO}" >/dev/null 2>&1 || true
done

for TARGET_REPO in "${WEBHOOK_LABEL_REPOS[@]}"; do
  configure_repo_webhook "${TARGET_REPO}"
done

REPO_LIST="$(IFS=,; printf '%s' "${WEBHOOK_LABEL_REPOS[*]}")"
log "GitHub bootstrap repositories configured: platform=${PLATFORM_REPO}, first-project=${PROJECT_REPO}, webhook-label-repos=${REPO_LIST}"
