#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1091
source "${ROOT_DIR}/lib.sh"
load_env_file "${BOOTSTRAP_ENV_FILE:?}"

: "${CODEXK8S_GITHUB_REPO:?CODEXK8S_GITHUB_REPO is required}"
: "${CODEXK8S_GITHUB_PAT:?CODEXK8S_GITHUB_PAT is required}"
: "${CODEXK8S_OPENAI_API_KEY:?CODEXK8S_OPENAI_API_KEY is required}"
: "${CODEXK8S_POSTGRES_PASSWORD:?CODEXK8S_POSTGRES_PASSWORD is required}"
: "${CODEXK8S_APP_SECRET_KEY:?CODEXK8S_APP_SECRET_KEY is required}"
: "${CODEXK8S_TOKEN_ENCRYPTION_KEY:?CODEXK8S_TOKEN_ENCRYPTION_KEY is required}"
: "${CODEXK8S_GITHUB_WEBHOOK_SECRET:?CODEXK8S_GITHUB_WEBHOOK_SECRET is required}"
: "${CODEXK8S_STAGING_DOMAIN:?CODEXK8S_STAGING_DOMAIN is required}"
: "${CODEXK8S_PUBLIC_BASE_URL:?CODEXK8S_PUBLIC_BASE_URL is required}"
: "${CODEXK8S_BOOTSTRAP_OWNER_EMAIL:?CODEXK8S_BOOTSTRAP_OWNER_EMAIL is required}"
: "${CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS:=}"
: "${CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS:=}"
: "${CODEXK8S_GITHUB_OAUTH_CLIENT_ID:?CODEXK8S_GITHUB_OAUTH_CLIENT_ID is required}"
: "${CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET:?CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET is required}"
: "${CODEXK8S_JWT_SIGNING_KEY:?CODEXK8S_JWT_SIGNING_KEY is required}"

CODEXK8S_STAGING_NAMESPACE="${CODEXK8S_STAGING_NAMESPACE:-codex-k8s-ai-staging}"
CODEXK8S_INTERNAL_REGISTRY_SERVICE="${CODEXK8S_INTERNAL_REGISTRY_SERVICE:-codex-k8s-registry}"
CODEXK8S_INTERNAL_REGISTRY_PORT="${CODEXK8S_INTERNAL_REGISTRY_PORT:-5000}"
CODEXK8S_INTERNAL_REGISTRY_STORAGE_SIZE="${CODEXK8S_INTERNAL_REGISTRY_STORAGE_SIZE:-20Gi}"
CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/web-console}"
CODEXK8S_INTERNAL_REGISTRY_HOST="${CODEXK8S_INTERNAL_REGISTRY_HOST:-127.0.0.1:${CODEXK8S_INTERNAL_REGISTRY_PORT}}"
CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/api-gateway}"
CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/control-plane}"
CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/worker}"
CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/agent-runner}"
CODEXK8S_API_GATEWAY_IMAGE="${CODEXK8S_API_GATEWAY_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_CONTROL_PLANE_IMAGE="${CODEXK8S_CONTROL_PLANE_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_WORKER_IMAGE="${CODEXK8S_WORKER_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_AGENT_RUNNER_IMAGE="${CODEXK8S_AGENT_RUNNER_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_WEB_CONSOLE_IMAGE="${CODEXK8S_WEB_CONSOLE_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_CONTROL_PLANE_MCP_BASE_URL="${CODEXK8S_CONTROL_PLANE_MCP_BASE_URL:-http://codex-k8s-control-plane.${CODEXK8S_STAGING_NAMESPACE}.svc.cluster.local:8081/mcp}"
CODEXK8S_WAIT_ROLLOUT="${CODEXK8S_WAIT_ROLLOUT:-true}"
CODEXK8S_ROLLOUT_TIMEOUT="${CODEXK8S_ROLLOUT_TIMEOUT:-1800s}"
CODEXK8S_RUNNER_SCALE_SET_NAME="${CODEXK8S_RUNNER_SCALE_SET_NAME:-codex-k8s-ai-staging}"
CODEXK8S_LEARNING_MODE_DEFAULT="${CODEXK8S_LEARNING_MODE_DEFAULT-true}"
CODEXK8S_KANIKO_TIMEOUT="${CODEXK8S_KANIKO_TIMEOUT:-1800s}"
CODEXK8S_KANIKO_CACHE_ENABLED="${CODEXK8S_KANIKO_CACHE_ENABLED:-true}"
CODEXK8S_KANIKO_CACHE_REPO="${CODEXK8S_KANIKO_CACHE_REPO:-}"
CODEXK8S_KANIKO_CACHE_TTL="${CODEXK8S_KANIKO_CACHE_TTL:-168h}"
CODEXK8S_KANIKO_CACHE_COMPRESSED="${CODEXK8S_KANIKO_CACHE_COMPRESSED:-false}"
CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL="${CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL:-4}"
CODEXK8S_GITHUB_WEBHOOK_URL="${CODEXK8S_GITHUB_WEBHOOK_URL:-https://${CODEXK8S_STAGING_DOMAIN}/api/v1/webhooks/github}"
CODEXK8S_GITHUB_WEBHOOK_EVENTS="${CODEXK8S_GITHUB_WEBHOOK_EVENTS:-push,pull_request,issues,issue_comment,pull_request_review,pull_request_review_comment}"
CODEXK8S_WORKER_REPLICAS="${CODEXK8S_WORKER_REPLICAS:-1}"
CODEXK8S_WORKER_POLL_INTERVAL="${CODEXK8S_WORKER_POLL_INTERVAL:-5s}"
CODEXK8S_WORKER_CLAIM_LIMIT="${CODEXK8S_WORKER_CLAIM_LIMIT:-2}"
CODEXK8S_WORKER_RUNNING_CHECK_LIMIT="${CODEXK8S_WORKER_RUNNING_CHECK_LIMIT:-200}"
CODEXK8S_WORKER_SLOTS_PER_PROJECT="${CODEXK8S_WORKER_SLOTS_PER_PROJECT:-2}"
CODEXK8S_WORKER_SLOT_LEASE_TTL="${CODEXK8S_WORKER_SLOT_LEASE_TTL:-10m}"
CODEXK8S_WORKER_K8S_NAMESPACE="${CODEXK8S_WORKER_K8S_NAMESPACE:-$CODEXK8S_STAGING_NAMESPACE}"
CODEXK8S_WORKER_JOB_IMAGE="${CODEXK8S_WORKER_JOB_IMAGE:-$CODEXK8S_AGENT_RUNNER_IMAGE}"
CODEXK8S_WORKER_JOB_COMMAND="${CODEXK8S_WORKER_JOB_COMMAND:-/usr/local/bin/codex-k8s-agent-runner}"
CODEXK8S_WORKER_JOB_TTL_SECONDS="${CODEXK8S_WORKER_JOB_TTL_SECONDS:-600}"
CODEXK8S_WORKER_JOB_BACKOFF_LIMIT="${CODEXK8S_WORKER_JOB_BACKOFF_LIMIT:-0}"
CODEXK8S_WORKER_JOB_ACTIVE_DEADLINE_SECONDS="${CODEXK8S_WORKER_JOB_ACTIVE_DEADLINE_SECONDS:-900}"
CODEXK8S_WORKER_RUN_NAMESPACE_PREFIX="${CODEXK8S_WORKER_RUN_NAMESPACE_PREFIX:-codex-issue}"
CODEXK8S_WORKER_RUN_NAMESPACE_CLEANUP="${CODEXK8S_WORKER_RUN_NAMESPACE_CLEANUP:-true}"
CODEXK8S_WORKER_RUN_SERVICE_ACCOUNT="${CODEXK8S_WORKER_RUN_SERVICE_ACCOUNT:-codex-runner}"
CODEXK8S_WORKER_RUN_ROLE_NAME="${CODEXK8S_WORKER_RUN_ROLE_NAME:-codex-runner}"
CODEXK8S_WORKER_RUN_ROLE_BINDING_NAME="${CODEXK8S_WORKER_RUN_ROLE_BINDING_NAME:-codex-runner}"
CODEXK8S_WORKER_RUN_RESOURCE_QUOTA_NAME="${CODEXK8S_WORKER_RUN_RESOURCE_QUOTA_NAME:-codex-run-quota}"
CODEXK8S_WORKER_RUN_LIMIT_RANGE_NAME="${CODEXK8S_WORKER_RUN_LIMIT_RANGE_NAME:-codex-run-limits}"
CODEXK8S_WORKER_RUN_CREDENTIALS_SECRET_NAME="${CODEXK8S_WORKER_RUN_CREDENTIALS_SECRET_NAME:-codex-run-credentials}"
CODEXK8S_WORKER_RUN_QUOTA_PODS="${CODEXK8S_WORKER_RUN_QUOTA_PODS:-20}"
CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_CPU="${CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_CPU:-4}"
CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_MEMORY="${CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_MEMORY:-8Gi}"
CODEXK8S_WORKER_RUN_QUOTA_LIMITS_CPU="${CODEXK8S_WORKER_RUN_QUOTA_LIMITS_CPU:-8}"
CODEXK8S_WORKER_RUN_QUOTA_LIMITS_MEMORY="${CODEXK8S_WORKER_RUN_QUOTA_LIMITS_MEMORY:-16Gi}"
CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_CPU="${CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_CPU:-250m}"
CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_MEMORY="${CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_MEMORY:-256Mi}"
CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_CPU="${CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_CPU:-1}"
CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_MEMORY="${CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_MEMORY:-1Gi}"
CODEXK8S_AGENT_DEFAULT_MODEL="${CODEXK8S_AGENT_DEFAULT_MODEL:-gpt-5.3-codex}"
CODEXK8S_AGENT_DEFAULT_REASONING_EFFORT="${CODEXK8S_AGENT_DEFAULT_REASONING_EFFORT:-high}"
CODEXK8S_AGENT_DEFAULT_LOCALE="${CODEXK8S_AGENT_DEFAULT_LOCALE:-ru}"
CODEXK8S_AGENT_BASE_BRANCH="${CODEXK8S_AGENT_BASE_BRANCH:-main}"
CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_CPU="${CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_CPU:-100m}"
CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_MEMORY="${CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_MEMORY:-256Mi}"
CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_CPU="${CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_CPU:-1000m}"
CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_MEMORY="${CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_MEMORY:-1Gi}"
CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_CPU="${CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_CPU:-100m}"
CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_MEMORY="${CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_MEMORY:-256Mi}"
CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_CPU="${CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_CPU:-1000m}"
CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_MEMORY="${CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_MEMORY:-1Gi}"
CODEXK8S_WORKER_RESOURCES_REQUEST_CPU="${CODEXK8S_WORKER_RESOURCES_REQUEST_CPU:-100m}"
CODEXK8S_WORKER_RESOURCES_REQUEST_MEMORY="${CODEXK8S_WORKER_RESOURCES_REQUEST_MEMORY:-256Mi}"
CODEXK8S_WORKER_RESOURCES_LIMIT_CPU="${CODEXK8S_WORKER_RESOURCES_LIMIT_CPU:-1000m}"
CODEXK8S_WORKER_RESOURCES_LIMIT_MEMORY="${CODEXK8S_WORKER_RESOURCES_LIMIT_MEMORY:-1Gi}"
CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_CPU="${CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_CPU:-100m}"
CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_MEMORY="${CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_MEMORY:-128Mi}"
CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_CPU="${CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_CPU:-500m}"
CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_MEMORY="${CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_MEMORY:-512Mi}"
CODEXK8S_KANIKO_RESOURCES_REQUEST_CPU="${CODEXK8S_KANIKO_RESOURCES_REQUEST_CPU:-8}"
CODEXK8S_KANIKO_RESOURCES_REQUEST_MEMORY="${CODEXK8S_KANIKO_RESOURCES_REQUEST_MEMORY:-16Gi}"
CODEXK8S_KANIKO_RESOURCES_LIMIT_CPU="${CODEXK8S_KANIKO_RESOURCES_LIMIT_CPU:-16}"
CODEXK8S_KANIKO_RESOURCES_LIMIT_MEMORY="${CODEXK8S_KANIKO_RESOURCES_LIMIT_MEMORY:-32Gi}"
CODEXK8S_JWT_TTL="${CODEXK8S_JWT_TTL:-15m}"
CODEXK8S_MCP_TOKEN_TTL="${CODEXK8S_MCP_TOKEN_TTL:-24h}"
CODEXK8S_MCP_TOKEN_SIGNING_KEY="${CODEXK8S_MCP_TOKEN_SIGNING_KEY:-}"
CODEXK8S_GIT_BOT_USERNAME="${CODEXK8S_GIT_BOT_USERNAME:-codex-bot}"
CODEXK8S_GIT_BOT_MAIL="${CODEXK8S_GIT_BOT_MAIL:-codex-bot@codex-k8s.local}"
CODEXK8S_GIT_BOT_TOKEN="${CODEXK8S_GIT_BOT_TOKEN:-}"
CODEXK8S_K8S_API_CIDR="${CODEXK8S_K8S_API_CIDR:-0.0.0.0/0}"
CODEXK8S_K8S_API_PORT="${CODEXK8S_K8S_API_PORT:-6443}"
[ -n "${CODEXK8S_GIT_BOT_TOKEN}" ] || die "CODEXK8S_GIT_BOT_TOKEN is required"

log "Configure GitHub repository variables/secrets for ${CODEXK8S_GITHUB_REPO}"
printf %s "${CODEXK8S_GITHUB_PAT}" | gh auth login --with-token

set_repo_var() {
  local key="$1"
  local default_value="$2"
  local value="${!key:-$default_value}"
  gh variable set "${key}" -R "${CODEXK8S_GITHUB_REPO}" --body "${value}"
}

get_repo_var() {
  local key="$1"
  local default_value="$2"
  printf '%s' "${!key:-$default_value}"
}

ensure_repo_label() {
  local name="$1"
  local description="$2"
  [ -n "$name" ] || return 0

  if gh label view "$name" -R "${CODEXK8S_GITHUB_REPO}" >/dev/null 2>&1; then
    gh label edit "$name" -R "${CODEXK8S_GITHUB_REPO}" --description "$description" >/dev/null
    return 0
  fi

  gh label create "$name" -R "${CODEXK8S_GITHUB_REPO}" --description "$description" >/dev/null
}

# Variables used by staging deploy workflow.
gh variable set CODEXK8S_STAGING_NAMESPACE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_STAGING_NAMESPACE}"
gh variable set CODEXK8S_INTERNAL_REGISTRY_SERVICE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_INTERNAL_REGISTRY_SERVICE}"
gh variable set CODEXK8S_INTERNAL_REGISTRY_PORT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_INTERNAL_REGISTRY_PORT}"
gh variable set CODEXK8S_INTERNAL_REGISTRY_STORAGE_SIZE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_INTERNAL_REGISTRY_STORAGE_SIZE}"
gh variable set CODEXK8S_INTERNAL_REGISTRY_HOST -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_INTERNAL_REGISTRY_HOST}"
gh variable set CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY}"
gh variable set CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY}"
gh variable set CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY}"
gh variable set CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY}"
gh variable set CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY}"
gh variable set CODEXK8S_KANIKO_TIMEOUT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_KANIKO_TIMEOUT}"
gh variable set CODEXK8S_KANIKO_CACHE_ENABLED -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_KANIKO_CACHE_ENABLED}"
gh variable set CODEXK8S_KANIKO_CACHE_REPO -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_KANIKO_CACHE_REPO}"
gh variable set CODEXK8S_KANIKO_CACHE_TTL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_KANIKO_CACHE_TTL}"
gh variable set CODEXK8S_KANIKO_CACHE_COMPRESSED -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_KANIKO_CACHE_COMPRESSED}"
gh variable set CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL}"
gh variable set CODEXK8S_API_GATEWAY_IMAGE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_API_GATEWAY_IMAGE}"
gh variable set CODEXK8S_CONTROL_PLANE_IMAGE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_CONTROL_PLANE_IMAGE}"
gh variable set CODEXK8S_WORKER_IMAGE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_IMAGE}"
gh variable set CODEXK8S_AGENT_RUNNER_IMAGE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_AGENT_RUNNER_IMAGE}"
gh variable set CODEXK8S_WEB_CONSOLE_IMAGE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WEB_CONSOLE_IMAGE}"
gh variable set CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_CPU -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_CPU}"
gh variable set CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_MEMORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_MEMORY}"
gh variable set CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_CPU -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_CPU}"
gh variable set CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_MEMORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_MEMORY}"
gh variable set CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_CPU -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_CPU}"
gh variable set CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_MEMORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_MEMORY}"
gh variable set CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_CPU -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_CPU}"
gh variable set CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_MEMORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_MEMORY}"
gh variable set CODEXK8S_WORKER_RESOURCES_REQUEST_CPU -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RESOURCES_REQUEST_CPU}"
gh variable set CODEXK8S_WORKER_RESOURCES_REQUEST_MEMORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RESOURCES_REQUEST_MEMORY}"
gh variable set CODEXK8S_WORKER_RESOURCES_LIMIT_CPU -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RESOURCES_LIMIT_CPU}"
gh variable set CODEXK8S_WORKER_RESOURCES_LIMIT_MEMORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RESOURCES_LIMIT_MEMORY}"
gh variable set CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_CPU -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_CPU}"
gh variable set CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_MEMORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_MEMORY}"
gh variable set CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_CPU -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_CPU}"
gh variable set CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_MEMORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_MEMORY}"
gh variable set CODEXK8S_KANIKO_RESOURCES_REQUEST_CPU -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_KANIKO_RESOURCES_REQUEST_CPU}"
gh variable set CODEXK8S_KANIKO_RESOURCES_REQUEST_MEMORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_KANIKO_RESOURCES_REQUEST_MEMORY}"
gh variable set CODEXK8S_KANIKO_RESOURCES_LIMIT_CPU -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_KANIKO_RESOURCES_LIMIT_CPU}"
gh variable set CODEXK8S_KANIKO_RESOURCES_LIMIT_MEMORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_KANIKO_RESOURCES_LIMIT_MEMORY}"
gh variable set CODEXK8S_K8S_API_CIDR -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_K8S_API_CIDR}"
gh variable set CODEXK8S_K8S_API_PORT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_K8S_API_PORT}"
gh variable set CODEXK8S_WAIT_ROLLOUT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WAIT_ROLLOUT}"
gh variable set CODEXK8S_ROLLOUT_TIMEOUT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_ROLLOUT_TIMEOUT}"
gh variable set CODEXK8S_STAGING_RUNNER -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_RUNNER_SCALE_SET_NAME}"
gh variable set CODEXK8S_WORKER_REPLICAS -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_REPLICAS}"
gh variable set CODEXK8S_WORKER_POLL_INTERVAL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_POLL_INTERVAL}"
gh variable set CODEXK8S_WORKER_CLAIM_LIMIT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_CLAIM_LIMIT}"
gh variable set CODEXK8S_WORKER_RUNNING_CHECK_LIMIT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUNNING_CHECK_LIMIT}"
gh variable set CODEXK8S_WORKER_SLOTS_PER_PROJECT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_SLOTS_PER_PROJECT}"
gh variable set CODEXK8S_WORKER_SLOT_LEASE_TTL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_SLOT_LEASE_TTL}"
gh variable set CODEXK8S_WORKER_K8S_NAMESPACE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_K8S_NAMESPACE}"
gh variable set CODEXK8S_WORKER_JOB_IMAGE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_JOB_IMAGE}"
gh variable set CODEXK8S_WORKER_JOB_COMMAND -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_JOB_COMMAND}"
gh variable set CODEXK8S_WORKER_JOB_TTL_SECONDS -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_JOB_TTL_SECONDS}"
gh variable set CODEXK8S_WORKER_JOB_BACKOFF_LIMIT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_JOB_BACKOFF_LIMIT}"
gh variable set CODEXK8S_WORKER_JOB_ACTIVE_DEADLINE_SECONDS -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_JOB_ACTIVE_DEADLINE_SECONDS}"
gh variable set CODEXK8S_WORKER_RUN_NAMESPACE_PREFIX -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_NAMESPACE_PREFIX}"
gh variable set CODEXK8S_WORKER_RUN_NAMESPACE_CLEANUP -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_NAMESPACE_CLEANUP}"
gh variable set CODEXK8S_WORKER_RUN_SERVICE_ACCOUNT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_SERVICE_ACCOUNT}"
gh variable set CODEXK8S_WORKER_RUN_ROLE_NAME -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_ROLE_NAME}"
gh variable set CODEXK8S_WORKER_RUN_ROLE_BINDING_NAME -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_ROLE_BINDING_NAME}"
gh variable set CODEXK8S_WORKER_RUN_RESOURCE_QUOTA_NAME -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_RESOURCE_QUOTA_NAME}"
gh variable set CODEXK8S_WORKER_RUN_LIMIT_RANGE_NAME -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_LIMIT_RANGE_NAME}"
gh variable set CODEXK8S_WORKER_RUN_CREDENTIALS_SECRET_NAME -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_CREDENTIALS_SECRET_NAME}"
gh variable set CODEXK8S_WORKER_RUN_QUOTA_PODS -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_QUOTA_PODS}"
gh variable set CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_CPU -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_CPU}"
gh variable set CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_MEMORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_MEMORY}"
gh variable set CODEXK8S_WORKER_RUN_QUOTA_LIMITS_CPU -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_QUOTA_LIMITS_CPU}"
gh variable set CODEXK8S_WORKER_RUN_QUOTA_LIMITS_MEMORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_QUOTA_LIMITS_MEMORY}"
gh variable set CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_CPU -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_CPU}"
gh variable set CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_MEMORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_MEMORY}"
gh variable set CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_CPU -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_CPU}"
gh variable set CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_MEMORY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_MEMORY}"
gh variable set CODEXK8S_AGENT_DEFAULT_MODEL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_AGENT_DEFAULT_MODEL}"
gh variable set CODEXK8S_AGENT_DEFAULT_REASONING_EFFORT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_AGENT_DEFAULT_REASONING_EFFORT}"
gh variable set CODEXK8S_AGENT_DEFAULT_LOCALE -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_AGENT_DEFAULT_LOCALE}"
gh variable set CODEXK8S_AGENT_BASE_BRANCH -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_AGENT_BASE_BRANCH}"
gh variable set CODEXK8S_GIT_BOT_USERNAME -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GIT_BOT_USERNAME}"
gh variable set CODEXK8S_GIT_BOT_MAIL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GIT_BOT_MAIL}"
gh variable set CODEXK8S_CONTROL_PLANE_MCP_BASE_URL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_CONTROL_PLANE_MCP_BASE_URL}"
if [ -n "${CODEXK8S_LEARNING_MODE_DEFAULT}" ]; then
  gh variable set CODEXK8S_LEARNING_MODE_DEFAULT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_LEARNING_MODE_DEFAULT}"
else
  gh variable delete CODEXK8S_LEARNING_MODE_DEFAULT -R "${CODEXK8S_GITHUB_REPO}" >/dev/null 2>&1 || true
fi
gh variable set CODEXK8S_GITHUB_WEBHOOK_URL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GITHUB_WEBHOOK_URL}"
gh variable set CODEXK8S_GITHUB_WEBHOOK_EVENTS -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GITHUB_WEBHOOK_EVENTS}"
set_repo_var RUN_INTAKE_LABEL "run:intake"
set_repo_var RUN_INTAKE_REVISE_LABEL "run:intake:revise"
set_repo_var RUN_VISION_LABEL "run:vision"
set_repo_var RUN_VISION_REVISE_LABEL "run:vision:revise"
set_repo_var RUN_PRD_LABEL "run:prd"
set_repo_var RUN_PRD_REVISE_LABEL "run:prd:revise"
set_repo_var RUN_ARCH_LABEL "run:arch"
set_repo_var RUN_ARCH_REVISE_LABEL "run:arch:revise"
set_repo_var RUN_DESIGN_LABEL "run:design"
set_repo_var RUN_DESIGN_REVISE_LABEL "run:design:revise"
set_repo_var RUN_PLAN_LABEL "run:plan"
set_repo_var RUN_PLAN_REVISE_LABEL "run:plan:revise"
set_repo_var RUN_DEV_LABEL "run:dev"
set_repo_var RUN_DEV_REVISE_LABEL "run:dev:revise"
set_repo_var RUN_DEBUG_LABEL "run:debug"
set_repo_var RUN_DOC_AUDIT_LABEL "run:doc-audit"
set_repo_var RUN_QA_LABEL "run:qa"
set_repo_var RUN_RELEASE_LABEL "run:release"
set_repo_var RUN_POSTDEPLOY_LABEL "run:postdeploy"
set_repo_var RUN_OPS_LABEL "run:ops"
set_repo_var RUN_ABORT_LABEL "run:abort"
set_repo_var RUN_RETHINK_LABEL "run:rethink"
set_repo_var STATE_BLOCKED_LABEL "state:blocked"
set_repo_var STATE_IN_REVIEW_LABEL "state:in-review"
set_repo_var STATE_APPROVED_LABEL "state:approved"
set_repo_var STATE_SUPERSEDED_LABEL "state:superseded"
set_repo_var STATE_ABANDONED_LABEL "state:abandoned"
set_repo_var NEED_INPUT_LABEL "need:input"
set_repo_var NEED_PM_LABEL "need:pm"
set_repo_var NEED_SA_LABEL "need:sa"
set_repo_var NEED_QA_LABEL "need:qa"
set_repo_var NEED_SRE_LABEL "need:sre"

# Ensure label catalog exists in repository (color is intentionally omitted;
# GitHub assigns one automatically if not provided).
ensure_repo_label "$(get_repo_var RUN_INTAKE_LABEL "run:intake")" "Start intake stage run"
ensure_repo_label "$(get_repo_var RUN_INTAKE_REVISE_LABEL "run:intake:revise")" "Request intake stage revision"
ensure_repo_label "$(get_repo_var RUN_VISION_LABEL "run:vision")" "Start vision stage run"
ensure_repo_label "$(get_repo_var RUN_VISION_REVISE_LABEL "run:vision:revise")" "Request vision stage revision"
ensure_repo_label "$(get_repo_var RUN_PRD_LABEL "run:prd")" "Start PRD stage run"
ensure_repo_label "$(get_repo_var RUN_PRD_REVISE_LABEL "run:prd:revise")" "Request PRD stage revision"
ensure_repo_label "$(get_repo_var RUN_ARCH_LABEL "run:arch")" "Start architecture stage run"
ensure_repo_label "$(get_repo_var RUN_ARCH_REVISE_LABEL "run:arch:revise")" "Request architecture stage revision"
ensure_repo_label "$(get_repo_var RUN_DESIGN_LABEL "run:design")" "Start design stage run"
ensure_repo_label "$(get_repo_var RUN_DESIGN_REVISE_LABEL "run:design:revise")" "Request design stage revision"
ensure_repo_label "$(get_repo_var RUN_PLAN_LABEL "run:plan")" "Start planning stage run"
ensure_repo_label "$(get_repo_var RUN_PLAN_REVISE_LABEL "run:plan:revise")" "Request planning stage revision"
ensure_repo_label "$(get_repo_var RUN_DEV_LABEL "run:dev")" "Start development run"
ensure_repo_label "$(get_repo_var RUN_DEV_REVISE_LABEL "run:dev:revise")" "Request development revision"
ensure_repo_label "$(get_repo_var RUN_DEBUG_LABEL "run:debug")" "Retain run namespace for debugging (skip auto cleanup)"
ensure_repo_label "$(get_repo_var RUN_DOC_AUDIT_LABEL "run:doc-audit")" "Start documentation audit run"
ensure_repo_label "$(get_repo_var RUN_QA_LABEL "run:qa")" "Start QA run"
ensure_repo_label "$(get_repo_var RUN_RELEASE_LABEL "run:release")" "Start release run"
ensure_repo_label "$(get_repo_var RUN_POSTDEPLOY_LABEL "run:postdeploy")" "Start post-deploy checks run"
ensure_repo_label "$(get_repo_var RUN_OPS_LABEL "run:ops")" "Start operations run"
ensure_repo_label "$(get_repo_var RUN_ABORT_LABEL "run:abort")" "Abort current stage run"
ensure_repo_label "$(get_repo_var RUN_RETHINK_LABEL "run:rethink")" "Reopen problem framing and scope"
ensure_repo_label "$(get_repo_var STATE_BLOCKED_LABEL "state:blocked")" "Issue is blocked"
ensure_repo_label "$(get_repo_var STATE_IN_REVIEW_LABEL "state:in-review")" "Work is in review"
ensure_repo_label "$(get_repo_var STATE_APPROVED_LABEL "state:approved")" "Work is approved"
ensure_repo_label "$(get_repo_var STATE_SUPERSEDED_LABEL "state:superseded")" "Issue superseded by newer scope"
ensure_repo_label "$(get_repo_var STATE_ABANDONED_LABEL "state:abandoned")" "Issue intentionally abandoned"
ensure_repo_label "$(get_repo_var NEED_INPUT_LABEL "need:input")" "Need additional input"
ensure_repo_label "$(get_repo_var NEED_PM_LABEL "need:pm")" "Need product management input"
ensure_repo_label "$(get_repo_var NEED_SA_LABEL "need:sa")" "Need solution architecture input"
ensure_repo_label "$(get_repo_var NEED_QA_LABEL "need:qa")" "Need QA input"
ensure_repo_label "$(get_repo_var NEED_SRE_LABEL "need:sre")" "Need SRE input"
gh variable set CODEXK8S_STAGING_DOMAIN -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_STAGING_DOMAIN}"
gh variable set CODEXK8S_PUBLIC_BASE_URL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_PUBLIC_BASE_URL}"
gh variable set CODEXK8S_BOOTSTRAP_OWNER_EMAIL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_BOOTSTRAP_OWNER_EMAIL}"
if [ -n "${CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS}" ]; then
  gh variable set CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS}"
else
  gh variable delete CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS -R "${CODEXK8S_GITHUB_REPO}" >/dev/null 2>&1 || true
fi
if [ -n "${CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS}" ]; then
  gh variable set CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS}"
else
  gh variable delete CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS -R "${CODEXK8S_GITHUB_REPO}" >/dev/null 2>&1 || true
fi
gh variable set CODEXK8S_GITHUB_OAUTH_CLIENT_ID -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GITHUB_OAUTH_CLIENT_ID}"
gh variable set CODEXK8S_JWT_TTL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_JWT_TTL}"
gh variable set CODEXK8S_MCP_TOKEN_TTL -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_MCP_TOKEN_TTL}"
if [ -n "${CODEXK8S_POSTGRES_DB:-}" ]; then
  gh variable set CODEXK8S_POSTGRES_DB -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_POSTGRES_DB}"
fi
if [ -n "${CODEXK8S_POSTGRES_USER:-}" ]; then
  gh variable set CODEXK8S_POSTGRES_USER -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_POSTGRES_USER}"
fi

# Secrets used by staging deploy workflow.
gh secret set CODEXK8S_OPENAI_API_KEY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_OPENAI_API_KEY}"
gh secret set CODEXK8S_POSTGRES_PASSWORD -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_POSTGRES_PASSWORD}"
gh secret set CODEXK8S_APP_SECRET_KEY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_APP_SECRET_KEY}"
gh secret set CODEXK8S_TOKEN_ENCRYPTION_KEY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_TOKEN_ENCRYPTION_KEY}"
gh secret set CODEXK8S_GITHUB_WEBHOOK_SECRET -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GITHUB_WEBHOOK_SECRET}"
gh secret set CODEXK8S_GITHUB_PAT -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GITHUB_PAT}"
gh secret set CODEXK8S_GIT_BOT_TOKEN -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GIT_BOT_TOKEN}"
gh secret set CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET}"
gh secret set CODEXK8S_JWT_SIGNING_KEY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_JWT_SIGNING_KEY}"
if [ -n "${CODEXK8S_MCP_TOKEN_SIGNING_KEY}" ]; then
  gh secret set CODEXK8S_MCP_TOKEN_SIGNING_KEY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_MCP_TOKEN_SIGNING_KEY}"
else
  gh secret delete CODEXK8S_MCP_TOKEN_SIGNING_KEY -R "${CODEXK8S_GITHUB_REPO}" >/dev/null 2>&1 || true
fi
if [ -n "${CODEXK8S_CONTEXT7_API_KEY:-}" ]; then
  gh secret set CODEXK8S_CONTEXT7_API_KEY -R "${CODEXK8S_GITHUB_REPO}" --body "${CODEXK8S_CONTEXT7_API_KEY}"
fi

# Cleanup legacy non-prefixed names to keep a single naming convention.
for legacy_secret in OPENAI_API_KEY CONTEXT7_API_KEY; do
  gh secret delete "${legacy_secret}" -R "${CODEXK8S_GITHUB_REPO}" >/dev/null 2>&1 || true
done
for legacy_secret in CODEXK8S_GITHUB_TOKEN CODEXK8S_GITHUB_USERNAME; do
  gh secret delete "${legacy_secret}" -R "${CODEXK8S_GITHUB_REPO}" >/dev/null 2>&1 || true
done
for legacy_var in STAGING_NAMESPACE STAGING_DOMAIN POSTGRES_DB POSTGRES_USER LEARNING_MODE_DEFAULT RUNNER_NAMESPACE RUNNER_SCALE_SET_NAME RUNNER_MIN RUNNER_MAX RUNNER_IMAGE CODEXK8S_GITHUB_USERNAME CODEXK8S_IMAGE CODEXK8S_INTERNAL_IMAGE_REPOSITORY; do
  gh variable delete "${legacy_var}" -R "${CODEXK8S_GITHUB_REPO}" >/dev/null 2>&1 || true
done

log "Configure GitHub repository webhook: ${CODEXK8S_GITHUB_WEBHOOK_URL}"
HOOK_ID="$(
  gh api "repos/${CODEXK8S_GITHUB_REPO}/hooks" \
    --jq ".[] | select(.config.url == \"${CODEXK8S_GITHUB_WEBHOOK_URL}\") | .id" \
    | head -n1 || true
)"

IFS=',' read -r -a WEBHOOK_EVENTS <<< "${CODEXK8S_GITHUB_WEBHOOK_EVENTS}"
WEBHOOK_API_ARGS=(
  -f "config[url]=${CODEXK8S_GITHUB_WEBHOOK_URL}"
  -f "config[content_type]=json"
  -f "config[insecure_ssl]=0"
  -f "config[secret]=${CODEXK8S_GITHUB_WEBHOOK_SECRET}"
  -F "active=true"
)

for event in "${WEBHOOK_EVENTS[@]}"; do
  trimmed="$(printf '%s' "$event" | xargs)"
  [ -n "$trimmed" ] || continue
  WEBHOOK_API_ARGS+=(-f "events[]=${trimmed}")
done

if [ -n "${HOOK_ID}" ]; then
  gh api "repos/${CODEXK8S_GITHUB_REPO}/hooks/${HOOK_ID}" -X PATCH "${WEBHOOK_API_ARGS[@]}" >/dev/null
  log "Updated webhook id=${HOOK_ID}"
else
  gh api "repos/${CODEXK8S_GITHUB_REPO}/hooks" -X POST -f "name=web" "${WEBHOOK_API_ARGS[@]}" >/dev/null
  log "Created webhook for ${CODEXK8S_GITHUB_WEBHOOK_URL}"
fi

log "GitHub repository bootstrap CI settings configured"
