#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1091
source "${ROOT_DIR}/lib.sh"
load_env_file "${BOOTSTRAP_ENV_FILE:?}"

kube_env

REPO_DIR="$(repo_dir)"
: "${CODEXK8S_GITHUB_REPO:?CODEXK8S_GITHUB_REPO is required}"
: "${CODEXK8S_GITHUB_PAT:?CODEXK8S_GITHUB_PAT is required}"

CODEXK8S_STAGING_NAMESPACE="${CODEXK8S_STAGING_NAMESPACE:-codex-k8s-ai-staging}"
CODEXK8S_INTERNAL_REGISTRY_SERVICE="${CODEXK8S_INTERNAL_REGISTRY_SERVICE:-codex-k8s-registry}"
CODEXK8S_INTERNAL_REGISTRY_PORT="${CODEXK8S_INTERNAL_REGISTRY_PORT:-5000}"
CODEXK8S_INTERNAL_REGISTRY_STORAGE_SIZE="${CODEXK8S_INTERNAL_REGISTRY_STORAGE_SIZE:-20Gi}"
CODEXK8S_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/codex-k8s}"
CODEXK8S_KANIKO_TIMEOUT="${CODEXK8S_KANIKO_TIMEOUT:-1800s}"
CODEXK8S_BUILD_REF="${CODEXK8S_BUILD_REF:-$(git -C "$REPO_DIR" rev-parse HEAD)}"
CODEXK8S_INTERNAL_REGISTRY_HOST="${CODEXK8S_INTERNAL_REGISTRY_HOST:-127.0.0.1:${CODEXK8S_INTERNAL_REGISTRY_PORT}}"
CODEXK8S_IMAGE="${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_INTERNAL_IMAGE_REPOSITORY}:latest"

log "Setup internal loopback registry (no auth) and build image with Kaniko"
export CODEXK8S_STAGING_NAMESPACE \
  CODEXK8S_GITHUB_REPO \
  CODEXK8S_GITHUB_PAT \
  CODEXK8S_INTERNAL_REGISTRY_SERVICE \
  CODEXK8S_INTERNAL_REGISTRY_PORT \
  CODEXK8S_INTERNAL_REGISTRY_STORAGE_SIZE \
  CODEXK8S_INTERNAL_REGISTRY_HOST \
  CODEXK8S_INTERNAL_IMAGE_REPOSITORY \
  CODEXK8S_KANIKO_TIMEOUT \
  CODEXK8S_BUILD_REF
bash "${REPO_DIR}/deploy/scripts/build_internal_image.sh"

set_env_var "${BOOTSTRAP_ENV_FILE}" "CODEXK8S_INTERNAL_REGISTRY_SERVICE" "${CODEXK8S_INTERNAL_REGISTRY_SERVICE}"
set_env_var "${BOOTSTRAP_ENV_FILE}" "CODEXK8S_INTERNAL_REGISTRY_PORT" "${CODEXK8S_INTERNAL_REGISTRY_PORT}"
set_env_var "${BOOTSTRAP_ENV_FILE}" "CODEXK8S_INTERNAL_REGISTRY_STORAGE_SIZE" "${CODEXK8S_INTERNAL_REGISTRY_STORAGE_SIZE}"
set_env_var "${BOOTSTRAP_ENV_FILE}" "CODEXK8S_INTERNAL_IMAGE_REPOSITORY" "${CODEXK8S_INTERNAL_IMAGE_REPOSITORY}"
set_env_var "${BOOTSTRAP_ENV_FILE}" "CODEXK8S_INTERNAL_REGISTRY_HOST" "${CODEXK8S_INTERNAL_REGISTRY_HOST}"
set_env_var "${BOOTSTRAP_ENV_FILE}" "CODEXK8S_KANIKO_TIMEOUT" "${CODEXK8S_KANIKO_TIMEOUT}"
set_env_var "${BOOTSTRAP_ENV_FILE}" "CODEXK8S_IMAGE" "${CODEXK8S_IMAGE}"

log "Internal image for deploy: ${CODEXK8S_IMAGE}"
