#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1091
source "${ROOT_DIR}/lib.sh"
load_env_file "${BOOTSTRAP_ENV_FILE:?}"

kube_env

REPO_DIR="$(repo_dir)"
CODEXK8S_STAGING_NAMESPACE="${CODEXK8S_STAGING_NAMESPACE:-codex-k8s-ai-staging}"
CODEXK8S_INTERNAL_REGISTRY_SERVICE="${CODEXK8S_INTERNAL_REGISTRY_SERVICE:-codex-k8s-registry}"
CODEXK8S_INTERNAL_REGISTRY_PORT="${CODEXK8S_INTERNAL_REGISTRY_PORT:-5000}"
CODEXK8S_INTERNAL_REGISTRY_HOST="${CODEXK8S_INTERNAL_REGISTRY_HOST:-127.0.0.1:${CODEXK8S_INTERNAL_REGISTRY_PORT}}"
CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/api-gateway}"
CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/control-plane}"
CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/worker}"
CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/web-console}"
CODEXK8S_API_GATEWAY_IMAGE="${CODEXK8S_API_GATEWAY_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_CONTROL_PLANE_IMAGE="${CODEXK8S_CONTROL_PLANE_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_WORKER_IMAGE="${CODEXK8S_WORKER_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_WEB_CONSOLE_IMAGE="${CODEXK8S_WEB_CONSOLE_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_WORKER_JOB_IMAGE="${CODEXK8S_WORKER_JOB_IMAGE:-${CODEXK8S_WORKER_IMAGE}}"
CODEXK8S_WAIT_ROLLOUT="${CODEXK8S_WAIT_ROLLOUT:-true}"
CODEXK8S_ROLLOUT_TIMEOUT="${CODEXK8S_ROLLOUT_TIMEOUT:-1800s}"
CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_CPU="${CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_CPU:-100m}"
CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_MEMORY="${CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_MEMORY:-256Mi}"
CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_CPU="${CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_CPU:-1000m}"
CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_MEMORY="${CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_MEMORY:-1Gi}"
CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_CPU="${CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_CPU:-100m}"
CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_MEMORY="${CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_MEMORY:-256Mi}"
CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_CPU="${CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_CPU:-1000m}"
CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_MEMORY="${CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_MEMORY:-1Gi}"
CODEXK8S_WORKER_RESOURCES_REQUEST_CPU="${CODEXK8S_WORKER_RESOURCES_REQUEST_CPU:-100m}"
CODEXK8S_WORKER_RESOURCES_REQUEST_MEMORY="${CODEXK8S_WORKER_RESOURCES_REQUEST_MEMORY:-256Mi}"
CODEXK8S_WORKER_RESOURCES_LIMIT_CPU="${CODEXK8S_WORKER_RESOURCES_LIMIT_CPU:-1000m}"
CODEXK8S_WORKER_RESOURCES_LIMIT_MEMORY="${CODEXK8S_WORKER_RESOURCES_LIMIT_MEMORY:-1Gi}"
CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_CPU="${CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_CPU:-50m}"
CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_MEMORY="${CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_MEMORY:-128Mi}"
CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_CPU="${CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_CPU:-500m}"
CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_MEMORY="${CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_MEMORY:-512Mi}"
CODEXK8S_KANIKO_CACHE_ENABLED="${CODEXK8S_KANIKO_CACHE_ENABLED:-true}"
CODEXK8S_KANIKO_CACHE_REPO="${CODEXK8S_KANIKO_CACHE_REPO:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/codex-k8s/kaniko-cache}"
CODEXK8S_KANIKO_CACHE_TTL="${CODEXK8S_KANIKO_CACHE_TTL:-168h}"
CODEXK8S_KANIKO_CACHE_COMPRESSED="${CODEXK8S_KANIKO_CACHE_COMPRESSED:-false}"
CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL="${CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL:-4}"
CODEXK8S_LETSENCRYPT_SERVER="${CODEXK8S_LETSENCRYPT_SERVER:-https://acme-v02.api.letsencrypt.org/directory}"
: "${CODEXK8S_STAGING_DOMAIN:?CODEXK8S_STAGING_DOMAIN is required}"
: "${CODEXK8S_LETSENCRYPT_EMAIL:?CODEXK8S_LETSENCRYPT_EMAIL is required}"
: "${CODEXK8S_GITHUB_WEBHOOK_SECRET:?CODEXK8S_GITHUB_WEBHOOK_SECRET is required}"
: "${CODEXK8S_PUBLIC_BASE_URL:?CODEXK8S_PUBLIC_BASE_URL is required}"
: "${CODEXK8S_BOOTSTRAP_OWNER_EMAIL:?CODEXK8S_BOOTSTRAP_OWNER_EMAIL is required}"
: "${CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS:=}"
: "${CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS:=}"
: "${CODEXK8S_GITHUB_OAUTH_CLIENT_ID:?CODEXK8S_GITHUB_OAUTH_CLIENT_ID is required}"
: "${CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET:?CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET is required}"
: "${CODEXK8S_JWT_SIGNING_KEY:?CODEXK8S_JWT_SIGNING_KEY is required}"
: "${CODEXK8S_JWT_TTL:=15m}"

ensure_domain_resolves "$CODEXK8S_STAGING_DOMAIN"

kubectl -n "$CODEXK8S_STAGING_NAMESPACE" create secret generic codex-k8s-postgres \
  --from-literal=CODEXK8S_POSTGRES_DB="${CODEXK8S_POSTGRES_DB}" \
  --from-literal=CODEXK8S_POSTGRES_USER="${CODEXK8S_POSTGRES_USER}" \
  --from-literal=CODEXK8S_POSTGRES_PASSWORD="${CODEXK8S_POSTGRES_PASSWORD}" \
  --dry-run=client -o yaml | kubectl apply -f -

kubectl -n "$CODEXK8S_STAGING_NAMESPACE" create secret generic codex-k8s-runtime \
  --from-literal=CODEXK8S_OPENAI_API_KEY="${CODEXK8S_OPENAI_API_KEY}" \
  --from-literal=CODEXK8S_CONTEXT7_API_KEY="${CODEXK8S_CONTEXT7_API_KEY:-}" \
  --from-literal=CODEXK8S_APP_SECRET_KEY="${CODEXK8S_APP_SECRET_KEY}" \
  --from-literal=CODEXK8S_TOKEN_ENCRYPTION_KEY="${CODEXK8S_TOKEN_ENCRYPTION_KEY}" \
  --from-literal=CODEXK8S_GITHUB_WEBHOOK_SECRET="${CODEXK8S_GITHUB_WEBHOOK_SECRET}" \
  --from-literal=CODEXK8S_PUBLIC_BASE_URL="${CODEXK8S_PUBLIC_BASE_URL}" \
  --from-literal=CODEXK8S_BOOTSTRAP_OWNER_EMAIL="${CODEXK8S_BOOTSTRAP_OWNER_EMAIL}" \
  --from-literal=CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS="${CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS}" \
  --from-literal=CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS="${CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS}" \
  --from-literal=CODEXK8S_GITHUB_OAUTH_CLIENT_ID="${CODEXK8S_GITHUB_OAUTH_CLIENT_ID}" \
  --from-literal=CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET="${CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET}" \
  --from-literal=CODEXK8S_JWT_SIGNING_KEY="${CODEXK8S_JWT_SIGNING_KEY}" \
  --from-literal=CODEXK8S_JWT_TTL="${CODEXK8S_JWT_TTL}" \
  --dry-run=client -o yaml | kubectl apply -f -

sed \
  -e "s|\${CODEXK8S_LETSENCRYPT_EMAIL}|${CODEXK8S_LETSENCRYPT_EMAIL}|g" \
  -e "s|\${CODEXK8S_LETSENCRYPT_SERVER}|${CODEXK8S_LETSENCRYPT_SERVER}|g" \
  "${REPO_DIR}/deploy/base/cert-manager/clusterissuer.yaml.tpl" | kubectl apply -f -
kubectl wait --for=condition=Ready clusterissuer/codex-k8s-letsencrypt --timeout=600s

export CODEXK8S_STAGING_NAMESPACE CODEXK8S_STAGING_DOMAIN CODEXK8S_API_GATEWAY_IMAGE CODEXK8S_CONTROL_PLANE_IMAGE CODEXK8S_WORKER_IMAGE CODEXK8S_WEB_CONSOLE_IMAGE CODEXK8S_WAIT_ROLLOUT CODEXK8S_ROLLOUT_TIMEOUT
export CODEXK8S_WORKER_REPLICAS CODEXK8S_WORKER_POLL_INTERVAL CODEXK8S_WORKER_CLAIM_LIMIT CODEXK8S_WORKER_RUNNING_CHECK_LIMIT CODEXK8S_WORKER_SLOTS_PER_PROJECT CODEXK8S_WORKER_SLOT_LEASE_TTL CODEXK8S_WORKER_K8S_NAMESPACE
export CODEXK8S_WORKER_JOB_IMAGE CODEXK8S_WORKER_JOB_COMMAND CODEXK8S_WORKER_JOB_TTL_SECONDS CODEXK8S_WORKER_JOB_BACKOFF_LIMIT CODEXK8S_WORKER_JOB_ACTIVE_DEADLINE_SECONDS
export CODEXK8S_WORKER_RUN_NAMESPACE_PREFIX CODEXK8S_WORKER_RUN_NAMESPACE_CLEANUP CODEXK8S_WORKER_RUN_SERVICE_ACCOUNT CODEXK8S_WORKER_RUN_ROLE_NAME CODEXK8S_WORKER_RUN_ROLE_BINDING_NAME
export CODEXK8S_WORKER_RUN_RESOURCE_QUOTA_NAME CODEXK8S_WORKER_RUN_LIMIT_RANGE_NAME CODEXK8S_WORKER_RUN_QUOTA_PODS CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_CPU CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_MEMORY
export CODEXK8S_WORKER_RUN_QUOTA_LIMITS_CPU CODEXK8S_WORKER_RUN_QUOTA_LIMITS_MEMORY CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_CPU CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_MEMORY CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_CPU CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_MEMORY
export CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_CPU CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_MEMORY CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_CPU CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_MEMORY
export CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_CPU CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_MEMORY CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_CPU CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_MEMORY
export CODEXK8S_WORKER_RESOURCES_REQUEST_CPU CODEXK8S_WORKER_RESOURCES_REQUEST_MEMORY CODEXK8S_WORKER_RESOURCES_LIMIT_CPU CODEXK8S_WORKER_RESOURCES_LIMIT_MEMORY
export CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_CPU CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_MEMORY CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_CPU CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_MEMORY
export CODEXK8S_KANIKO_CACHE_ENABLED CODEXK8S_KANIKO_CACHE_REPO CODEXK8S_KANIKO_CACHE_TTL CODEXK8S_KANIKO_CACHE_COMPRESSED CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL
bash "${REPO_DIR}/deploy/scripts/deploy_staging.sh"
