#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1091
source "${ROOT_DIR}/lib.sh"
load_env_file "${BOOTSTRAP_ENV_FILE:?}"

kube_env

REPO_DIR="$(repo_dir)"
CODEXK8S_STAGING_NAMESPACE="${CODEXK8S_STAGING_NAMESPACE:-codex-k8s-ai-staging}"
CODEXK8S_INTERNAL_REGISTRY_SERVICE="${CODEXK8S_INTERNAL_REGISTRY_SERVICE:-codex-k8s-registry}"
CODEXK8S_INTERNAL_REGISTRY_PORT="${CODEXK8S_INTERNAL_REGISTRY_PORT:-5000}"
CODEXK8S_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/codex-k8s}"
CODEXK8S_INTERNAL_REGISTRY_HOST="${CODEXK8S_INTERNAL_REGISTRY_HOST:-127.0.0.1:${CODEXK8S_INTERNAL_REGISTRY_PORT}}"
CODEXK8S_IMAGE="${CODEXK8S_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_WAIT_ROLLOUT="${CODEXK8S_WAIT_ROLLOUT:-true}"
CODEXK8S_ROLLOUT_TIMEOUT="${CODEXK8S_ROLLOUT_TIMEOUT:-1800s}"
CODEXK8S_LETSENCRYPT_SERVER="${CODEXK8S_LETSENCRYPT_SERVER:-https://acme-v02.api.letsencrypt.org/directory}"
: "${CODEXK8S_STAGING_DOMAIN:?CODEXK8S_STAGING_DOMAIN is required}"
: "${CODEXK8S_LETSENCRYPT_EMAIL:?CODEXK8S_LETSENCRYPT_EMAIL is required}"

ensure_domain_resolves "$CODEXK8S_STAGING_DOMAIN"

kubectl -n "$CODEXK8S_STAGING_NAMESPACE" create secret generic codex-k8s-postgres \
  --from-literal=CODEXK8S_POSTGRES_DB="${CODEXK8S_POSTGRES_DB}" \
  --from-literal=CODEXK8S_POSTGRES_USER="${CODEXK8S_POSTGRES_USER}" \
  --from-literal=CODEXK8S_POSTGRES_PASSWORD="${CODEXK8S_POSTGRES_PASSWORD}" \
  --dry-run=client -o yaml | kubectl apply -f -

kubectl -n "$CODEXK8S_STAGING_NAMESPACE" create secret generic codex-k8s-runtime \
  --from-literal=CODEXK8S_OPENAI_API_KEY="${CODEXK8S_OPENAI_API_KEY}" \
  --from-literal=CODEXK8S_CONTEXT7_API_KEY="${CODEXK8S_CONTEXT7_API_KEY:-}" \
  --from-literal=CODEXK8S_APP_SECRET_KEY="${CODEXK8S_APP_SECRET_KEY}" \
  --from-literal=CODEXK8S_TOKEN_ENCRYPTION_KEY="${CODEXK8S_TOKEN_ENCRYPTION_KEY}" \
  --dry-run=client -o yaml | kubectl apply -f -

sed \
  -e "s|\${CODEXK8S_LETSENCRYPT_EMAIL}|${CODEXK8S_LETSENCRYPT_EMAIL}|g" \
  -e "s|\${CODEXK8S_LETSENCRYPT_SERVER}|${CODEXK8S_LETSENCRYPT_SERVER}|g" \
  "${REPO_DIR}/deploy/base/cert-manager/clusterissuer.yaml.tpl" | kubectl apply -f -
kubectl wait --for=condition=Ready clusterissuer/codex-k8s-letsencrypt --timeout=600s

export CODEXK8S_STAGING_NAMESPACE CODEXK8S_STAGING_DOMAIN CODEXK8S_IMAGE CODEXK8S_WAIT_ROLLOUT CODEXK8S_ROLLOUT_TIMEOUT
bash "${REPO_DIR}/deploy/scripts/deploy_staging.sh"
