#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1091
source "${ROOT_DIR}/lib.sh"
load_env_file "${BOOTSTRAP_ENV_FILE:?}"

kube_env

REPO_DIR="$(repo_dir)"
CODEXK8S_STAGING_NAMESPACE="${CODEXK8S_STAGING_NAMESPACE:-codex-k8s-ai-staging}"
CODEXK8S_INTERNAL_REGISTRY_SERVICE="${CODEXK8S_INTERNAL_REGISTRY_SERVICE:-codex-k8s-registry}"
CODEXK8S_INTERNAL_REGISTRY_PORT="${CODEXK8S_INTERNAL_REGISTRY_PORT:-5000}"
CODEXK8S_INTERNAL_REGISTRY_HOST="${CODEXK8S_INTERNAL_REGISTRY_HOST:-127.0.0.1:${CODEXK8S_INTERNAL_REGISTRY_PORT}}"
CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/api-gateway}"
CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/control-plane}"
CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/worker}"
CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/agent-runner}"
CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/web-console}"
CODEXK8S_API_GATEWAY_IMAGE="${CODEXK8S_API_GATEWAY_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_CONTROL_PLANE_IMAGE="${CODEXK8S_CONTROL_PLANE_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_WORKER_IMAGE="${CODEXK8S_WORKER_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_AGENT_RUNNER_IMAGE="${CODEXK8S_AGENT_RUNNER_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_WEB_CONSOLE_IMAGE="${CODEXK8S_WEB_CONSOLE_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_WORKER_JOB_IMAGE="${CODEXK8S_WORKER_JOB_IMAGE:-}"
CODEXK8S_WORKER_JOB_COMMAND="${CODEXK8S_WORKER_JOB_COMMAND:-}"
CODEXK8S_CONTROL_PLANE_GRPC_TARGET="${CODEXK8S_CONTROL_PLANE_GRPC_TARGET:-codex-k8s-control-plane.${CODEXK8S_STAGING_NAMESPACE}.svc.cluster.local:9090}"
CODEXK8S_CONTROL_PLANE_MCP_BASE_URL="${CODEXK8S_CONTROL_PLANE_MCP_BASE_URL:-}"
CODEXK8S_WAIT_ROLLOUT="${CODEXK8S_WAIT_ROLLOUT:-true}"
CODEXK8S_ROLLOUT_TIMEOUT="${CODEXK8S_ROLLOUT_TIMEOUT:-1800s}"
CODEXK8S_WORKER_RUN_CREDENTIALS_SECRET_NAME="${CODEXK8S_WORKER_RUN_CREDENTIALS_SECRET_NAME:-}"
CODEXK8S_GITHUB_PAT="${CODEXK8S_GITHUB_PAT:-}"
CODEXK8S_GITHUB_REPO="${CODEXK8S_GITHUB_REPO:-}"
CODEXK8S_FIRST_PROJECT_GITHUB_REPO="${CODEXK8S_FIRST_PROJECT_GITHUB_REPO:-}"
CODEXK8S_OPENAI_API_KEY="${CODEXK8S_OPENAI_API_KEY:-}"
CODEXK8S_OPENAI_AUTH_FILE="${CODEXK8S_OPENAI_AUTH_FILE:-}"
CODEXK8S_PROJECT_DB_ADMIN_HOST="${CODEXK8S_PROJECT_DB_ADMIN_HOST:-}"
CODEXK8S_PROJECT_DB_ADMIN_PORT="${CODEXK8S_PROJECT_DB_ADMIN_PORT:-}"
CODEXK8S_PROJECT_DB_ADMIN_USER="${CODEXK8S_PROJECT_DB_ADMIN_USER:-}"
CODEXK8S_PROJECT_DB_ADMIN_PASSWORD="${CODEXK8S_PROJECT_DB_ADMIN_PASSWORD:-}"
CODEXK8S_PROJECT_DB_ADMIN_SSLMODE="${CODEXK8S_PROJECT_DB_ADMIN_SSLMODE:-}"
CODEXK8S_PROJECT_DB_ADMIN_DATABASE="${CODEXK8S_PROJECT_DB_ADMIN_DATABASE:-}"
CODEXK8S_PROJECT_DB_LIFECYCLE_ALLOWED_ENVS="${CODEXK8S_PROJECT_DB_LIFECYCLE_ALLOWED_ENVS:-}"
if [ -z "${CODEXK8S_AGENT_DEFAULT_MODEL:-}" ]; then
  if [ -n "${CODEXK8S_OPENAI_AUTH_FILE}" ]; then
    CODEXK8S_AGENT_DEFAULT_MODEL="gpt-5.3-codex"
  else
    CODEXK8S_AGENT_DEFAULT_MODEL="gpt-5.2-codex"
  fi
fi
CODEXK8S_AGENT_DEFAULT_REASONING_EFFORT="${CODEXK8S_AGENT_DEFAULT_REASONING_EFFORT:-}"
CODEXK8S_AGENT_DEFAULT_LOCALE="${CODEXK8S_AGENT_DEFAULT_LOCALE:-}"
CODEXK8S_AGENT_BASE_BRANCH="${CODEXK8S_AGENT_BASE_BRANCH:-}"
CODEXK8S_GIT_BOT_USERNAME="${CODEXK8S_GIT_BOT_USERNAME:-}"
CODEXK8S_GIT_BOT_MAIL="${CODEXK8S_GIT_BOT_MAIL:-}"
CODEXK8S_AI_MODEL_GPT_5_3_CODEX_LABEL="${CODEXK8S_AI_MODEL_GPT_5_3_CODEX_LABEL:-}"
CODEXK8S_AI_MODEL_GPT_5_3_CODEX_SPARK_LABEL="${CODEXK8S_AI_MODEL_GPT_5_3_CODEX_SPARK_LABEL:-}"
CODEXK8S_AI_MODEL_GPT_5_2_CODEX_LABEL="${CODEXK8S_AI_MODEL_GPT_5_2_CODEX_LABEL:-}"
CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MAX_LABEL="${CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MAX_LABEL:-}"
CODEXK8S_AI_MODEL_GPT_5_2_LABEL="${CODEXK8S_AI_MODEL_GPT_5_2_LABEL:-}"
CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MINI_LABEL="${CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MINI_LABEL:-}"
CODEXK8S_AI_REASONING_LOW_LABEL="${CODEXK8S_AI_REASONING_LOW_LABEL:-}"
CODEXK8S_AI_REASONING_MEDIUM_LABEL="${CODEXK8S_AI_REASONING_MEDIUM_LABEL:-}"
CODEXK8S_AI_REASONING_HIGH_LABEL="${CODEXK8S_AI_REASONING_HIGH_LABEL:-}"
CODEXK8S_AI_REASONING_EXTRA_HIGH_LABEL="${CODEXK8S_AI_REASONING_EXTRA_HIGH_LABEL:-}"
CODEXK8S_KANIKO_CACHE_ENABLED="${CODEXK8S_KANIKO_CACHE_ENABLED:-true}"
CODEXK8S_KANIKO_CACHE_REPO="${CODEXK8S_KANIKO_CACHE_REPO:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/codex-k8s/kaniko-cache}"
CODEXK8S_KANIKO_CACHE_TTL="${CODEXK8S_KANIKO_CACHE_TTL:-168h}"
CODEXK8S_KANIKO_CACHE_COMPRESSED="${CODEXK8S_KANIKO_CACHE_COMPRESSED:-false}"
CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL="${CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL:-4}"
CODEXK8S_LETSENCRYPT_SERVER="${CODEXK8S_LETSENCRYPT_SERVER:-https://acme-v02.api.letsencrypt.org/directory}"
: "${CODEXK8S_STAGING_DOMAIN:?CODEXK8S_STAGING_DOMAIN is required}"
: "${CODEXK8S_LETSENCRYPT_EMAIL:?CODEXK8S_LETSENCRYPT_EMAIL is required}"
: "${CODEXK8S_GITHUB_WEBHOOK_SECRET:?CODEXK8S_GITHUB_WEBHOOK_SECRET is required}"
: "${CODEXK8S_PUBLIC_BASE_URL:?CODEXK8S_PUBLIC_BASE_URL is required}"
: "${CODEXK8S_BOOTSTRAP_OWNER_EMAIL:?CODEXK8S_BOOTSTRAP_OWNER_EMAIL is required}"
: "${CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS:=}"
: "${CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS:=}"
: "${CODEXK8S_GITHUB_REPO:?CODEXK8S_GITHUB_REPO is required}"
: "${CODEXK8S_GITHUB_OAUTH_CLIENT_ID:?CODEXK8S_GITHUB_OAUTH_CLIENT_ID is required}"
: "${CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET:?CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET is required}"
: "${CODEXK8S_JWT_SIGNING_KEY:?CODEXK8S_JWT_SIGNING_KEY is required}"
: "${CODEXK8S_JWT_TTL:=}"
: "${CODEXK8S_MCP_TOKEN_SIGNING_KEY:=}"
: "${CODEXK8S_MCP_TOKEN_TTL:=}"
: "${CODEXK8S_RUN_AGENT_LOGS_RETENTION_DAYS:=}"
: "${CODEXK8S_GIT_BOT_TOKEN:?CODEXK8S_GIT_BOT_TOKEN is required}"

ensure_domain_resolves "$CODEXK8S_STAGING_DOMAIN"

if [ -z "${CODEXK8S_OPENAI_API_KEY}" ] && kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime >/dev/null 2>&1; then
  CODEXK8S_OPENAI_API_KEY="$(
    kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime \
      -o jsonpath='{.data.CODEXK8S_OPENAI_API_KEY}' 2>/dev/null | base64 -d || true
  )"
fi
if [ -z "${CODEXK8S_OPENAI_AUTH_FILE}" ] && kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime >/dev/null 2>&1; then
  CODEXK8S_OPENAI_AUTH_FILE="$(
    kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime \
      -o jsonpath='{.data.CODEXK8S_OPENAI_AUTH_FILE}' 2>/dev/null | base64 -d || true
  )"
fi
if [ -z "${CODEXK8S_GITHUB_PAT}" ] && kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime >/dev/null 2>&1; then
  CODEXK8S_GITHUB_PAT="$(
    kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime \
      -o jsonpath='{.data.CODEXK8S_GITHUB_PAT}' 2>/dev/null | base64 -d || true
  )"
fi
if [ -z "${CODEXK8S_PROJECT_DB_ADMIN_HOST}" ] && kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime >/dev/null 2>&1; then
  CODEXK8S_PROJECT_DB_ADMIN_HOST="$(
    kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime \
      -o jsonpath='{.data.CODEXK8S_PROJECT_DB_ADMIN_HOST}' 2>/dev/null | base64 -d || true
  )"
fi
if [ -z "${CODEXK8S_PROJECT_DB_ADMIN_PORT}" ] && kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime >/dev/null 2>&1; then
  CODEXK8S_PROJECT_DB_ADMIN_PORT="$(
    kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime \
      -o jsonpath='{.data.CODEXK8S_PROJECT_DB_ADMIN_PORT}' 2>/dev/null | base64 -d || true
  )"
fi
if [ -z "${CODEXK8S_PROJECT_DB_ADMIN_USER}" ] && kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime >/dev/null 2>&1; then
  CODEXK8S_PROJECT_DB_ADMIN_USER="$(
    kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime \
      -o jsonpath='{.data.CODEXK8S_PROJECT_DB_ADMIN_USER}' 2>/dev/null | base64 -d || true
  )"
fi
if [ -z "${CODEXK8S_PROJECT_DB_ADMIN_PASSWORD}" ] && kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime >/dev/null 2>&1; then
  CODEXK8S_PROJECT_DB_ADMIN_PASSWORD="$(
    kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime \
      -o jsonpath='{.data.CODEXK8S_PROJECT_DB_ADMIN_PASSWORD}' 2>/dev/null | base64 -d || true
  )"
fi
if [ -z "${CODEXK8S_PROJECT_DB_ADMIN_SSLMODE}" ] && kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime >/dev/null 2>&1; then
  CODEXK8S_PROJECT_DB_ADMIN_SSLMODE="$(
    kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime \
      -o jsonpath='{.data.CODEXK8S_PROJECT_DB_ADMIN_SSLMODE}' 2>/dev/null | base64 -d || true
  )"
fi
if [ -z "${CODEXK8S_PROJECT_DB_ADMIN_DATABASE}" ] && kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime >/dev/null 2>&1; then
  CODEXK8S_PROJECT_DB_ADMIN_DATABASE="$(
    kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime \
      -o jsonpath='{.data.CODEXK8S_PROJECT_DB_ADMIN_DATABASE}' 2>/dev/null | base64 -d || true
  )"
fi
if [ -z "${CODEXK8S_PROJECT_DB_LIFECYCLE_ALLOWED_ENVS}" ] && kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime >/dev/null 2>&1; then
  CODEXK8S_PROJECT_DB_LIFECYCLE_ALLOWED_ENVS="$(
    kubectl -n "$CODEXK8S_STAGING_NAMESPACE" get secret codex-k8s-runtime \
      -o jsonpath='{.data.CODEXK8S_PROJECT_DB_LIFECYCLE_ALLOWED_ENVS}' 2>/dev/null | base64 -d || true
  )"
fi
if [ -z "${CODEXK8S_OPENAI_API_KEY}" ] && [ -z "${CODEXK8S_OPENAI_AUTH_FILE}" ]; then
  die "Either CODEXK8S_OPENAI_API_KEY or CODEXK8S_OPENAI_AUTH_FILE is required"
fi

CODEXK8S_PROJECT_DB_ADMIN_HOST="${CODEXK8S_PROJECT_DB_ADMIN_HOST:-postgres}"
CODEXK8S_PROJECT_DB_ADMIN_PORT="${CODEXK8S_PROJECT_DB_ADMIN_PORT:-}"
CODEXK8S_PROJECT_DB_ADMIN_USER="${CODEXK8S_PROJECT_DB_ADMIN_USER:-${CODEXK8S_POSTGRES_USER:-codex_k8s}}"
CODEXK8S_PROJECT_DB_ADMIN_PASSWORD="${CODEXK8S_PROJECT_DB_ADMIN_PASSWORD:-${CODEXK8S_POSTGRES_PASSWORD:-}}"
CODEXK8S_PROJECT_DB_ADMIN_SSLMODE="${CODEXK8S_PROJECT_DB_ADMIN_SSLMODE:-}"
CODEXK8S_PROJECT_DB_ADMIN_DATABASE="${CODEXK8S_PROJECT_DB_ADMIN_DATABASE:-}"
[ -n "${CODEXK8S_PROJECT_DB_ADMIN_HOST}" ] || die "CODEXK8S_PROJECT_DB_ADMIN_HOST is required"
[ -n "${CODEXK8S_PROJECT_DB_ADMIN_USER}" ] || die "CODEXK8S_PROJECT_DB_ADMIN_USER is required"
[ -n "${CODEXK8S_PROJECT_DB_ADMIN_PASSWORD}" ] || die "CODEXK8S_PROJECT_DB_ADMIN_PASSWORD is required"

kubectl -n "$CODEXK8S_STAGING_NAMESPACE" create secret generic codex-k8s-postgres \
  --from-literal=CODEXK8S_POSTGRES_DB="${CODEXK8S_POSTGRES_DB}" \
  --from-literal=CODEXK8S_POSTGRES_USER="${CODEXK8S_POSTGRES_USER}" \
  --from-literal=CODEXK8S_POSTGRES_PASSWORD="${CODEXK8S_POSTGRES_PASSWORD}" \
  --dry-run=client -o yaml | kubectl apply -f -

kubectl -n "$CODEXK8S_STAGING_NAMESPACE" create secret generic codex-k8s-runtime \
  --from-literal=CODEXK8S_GITHUB_PAT="${CODEXK8S_GITHUB_PAT}" \
  --from-literal=CODEXK8S_GITHUB_REPO="${CODEXK8S_GITHUB_REPO}" \
  --from-literal=CODEXK8S_FIRST_PROJECT_GITHUB_REPO="${CODEXK8S_FIRST_PROJECT_GITHUB_REPO}" \
  --from-literal=CODEXK8S_OPENAI_API_KEY="${CODEXK8S_OPENAI_API_KEY}" \
  --from-literal=CODEXK8S_OPENAI_AUTH_FILE="${CODEXK8S_OPENAI_AUTH_FILE}" \
  --from-literal=CODEXK8S_PROJECT_DB_ADMIN_HOST="${CODEXK8S_PROJECT_DB_ADMIN_HOST}" \
  --from-literal=CODEXK8S_PROJECT_DB_ADMIN_PORT="${CODEXK8S_PROJECT_DB_ADMIN_PORT}" \
  --from-literal=CODEXK8S_PROJECT_DB_ADMIN_USER="${CODEXK8S_PROJECT_DB_ADMIN_USER}" \
  --from-literal=CODEXK8S_PROJECT_DB_ADMIN_PASSWORD="${CODEXK8S_PROJECT_DB_ADMIN_PASSWORD}" \
  --from-literal=CODEXK8S_PROJECT_DB_ADMIN_SSLMODE="${CODEXK8S_PROJECT_DB_ADMIN_SSLMODE}" \
  --from-literal=CODEXK8S_PROJECT_DB_ADMIN_DATABASE="${CODEXK8S_PROJECT_DB_ADMIN_DATABASE}" \
  --from-literal=CODEXK8S_PROJECT_DB_LIFECYCLE_ALLOWED_ENVS="${CODEXK8S_PROJECT_DB_LIFECYCLE_ALLOWED_ENVS}" \
  --from-literal=CODEXK8S_GIT_BOT_TOKEN="${CODEXK8S_GIT_BOT_TOKEN}" \
  --from-literal=CODEXK8S_GIT_BOT_USERNAME="${CODEXK8S_GIT_BOT_USERNAME}" \
  --from-literal=CODEXK8S_GIT_BOT_MAIL="${CODEXK8S_GIT_BOT_MAIL}" \
  --from-literal=CODEXK8S_CONTEXT7_API_KEY="${CODEXK8S_CONTEXT7_API_KEY:-}" \
  --from-literal=CODEXK8S_APP_SECRET_KEY="${CODEXK8S_APP_SECRET_KEY}" \
  --from-literal=CODEXK8S_TOKEN_ENCRYPTION_KEY="${CODEXK8S_TOKEN_ENCRYPTION_KEY}" \
  --from-literal=CODEXK8S_MCP_TOKEN_SIGNING_KEY="${CODEXK8S_MCP_TOKEN_SIGNING_KEY}" \
  --from-literal=CODEXK8S_MCP_TOKEN_TTL="${CODEXK8S_MCP_TOKEN_TTL}" \
  --from-literal=CODEXK8S_RUN_AGENT_LOGS_RETENTION_DAYS="${CODEXK8S_RUN_AGENT_LOGS_RETENTION_DAYS}" \
  --from-literal=CODEXK8S_GITHUB_WEBHOOK_SECRET="${CODEXK8S_GITHUB_WEBHOOK_SECRET}" \
  --from-literal=CODEXK8S_PUBLIC_BASE_URL="${CODEXK8S_PUBLIC_BASE_URL}" \
  --from-literal=CODEXK8S_BOOTSTRAP_OWNER_EMAIL="${CODEXK8S_BOOTSTRAP_OWNER_EMAIL}" \
  --from-literal=CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS="${CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS}" \
  --from-literal=CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS="${CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS}" \
  --from-literal=CODEXK8S_GITHUB_OAUTH_CLIENT_ID="${CODEXK8S_GITHUB_OAUTH_CLIENT_ID}" \
  --from-literal=CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET="${CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET}" \
  --from-literal=CODEXK8S_JWT_SIGNING_KEY="${CODEXK8S_JWT_SIGNING_KEY}" \
  --from-literal=CODEXK8S_JWT_TTL="${CODEXK8S_JWT_TTL}" \
  --dry-run=client -o yaml | kubectl apply -f -

sed \
  -e "s|\${CODEXK8S_LETSENCRYPT_EMAIL}|${CODEXK8S_LETSENCRYPT_EMAIL}|g" \
  -e "s|\${CODEXK8S_LETSENCRYPT_SERVER}|${CODEXK8S_LETSENCRYPT_SERVER}|g" \
  "${REPO_DIR}/deploy/base/cert-manager/clusterissuer.yaml.tpl" | kubectl apply -f -
kubectl wait --for=condition=Ready clusterissuer/codex-k8s-letsencrypt --timeout=600s

export CODEXK8S_STAGING_NAMESPACE CODEXK8S_STAGING_DOMAIN CODEXK8S_API_GATEWAY_IMAGE CODEXK8S_CONTROL_PLANE_IMAGE CODEXK8S_WORKER_IMAGE CODEXK8S_AGENT_RUNNER_IMAGE CODEXK8S_WEB_CONSOLE_IMAGE CODEXK8S_WAIT_ROLLOUT CODEXK8S_ROLLOUT_TIMEOUT
export CODEXK8S_WORKER_REPLICAS CODEXK8S_WORKER_POLL_INTERVAL CODEXK8S_WORKER_CLAIM_LIMIT CODEXK8S_WORKER_RUNNING_CHECK_LIMIT CODEXK8S_WORKER_SLOTS_PER_PROJECT CODEXK8S_WORKER_SLOT_LEASE_TTL CODEXK8S_WORKER_K8S_NAMESPACE
export CODEXK8S_WORKER_JOB_IMAGE CODEXK8S_WORKER_JOB_COMMAND CODEXK8S_WORKER_JOB_TTL_SECONDS CODEXK8S_WORKER_JOB_BACKOFF_LIMIT CODEXK8S_WORKER_JOB_ACTIVE_DEADLINE_SECONDS
export CODEXK8S_WORKER_RUN_NAMESPACE_PREFIX CODEXK8S_WORKER_RUN_NAMESPACE_CLEANUP CODEXK8S_WORKER_RUN_SERVICE_ACCOUNT CODEXK8S_WORKER_RUN_ROLE_NAME CODEXK8S_WORKER_RUN_ROLE_BINDING_NAME
export CODEXK8S_AGENT_DEFAULT_MODEL CODEXK8S_AGENT_DEFAULT_REASONING_EFFORT CODEXK8S_AGENT_DEFAULT_LOCALE CODEXK8S_AGENT_BASE_BRANCH
export CODEXK8S_GITHUB_PAT CODEXK8S_GITHUB_REPO CODEXK8S_FIRST_PROJECT_GITHUB_REPO CODEXK8S_OPENAI_API_KEY CODEXK8S_OPENAI_AUTH_FILE
export CODEXK8S_PROJECT_DB_ADMIN_HOST CODEXK8S_PROJECT_DB_ADMIN_PORT CODEXK8S_PROJECT_DB_ADMIN_USER CODEXK8S_PROJECT_DB_ADMIN_PASSWORD CODEXK8S_PROJECT_DB_ADMIN_SSLMODE CODEXK8S_PROJECT_DB_ADMIN_DATABASE CODEXK8S_PROJECT_DB_LIFECYCLE_ALLOWED_ENVS
export CODEXK8S_GIT_BOT_TOKEN CODEXK8S_GIT_BOT_USERNAME CODEXK8S_GIT_BOT_MAIL
export CODEXK8S_CONTROL_PLANE_GRPC_TARGET
export CODEXK8S_CONTROL_PLANE_MCP_BASE_URL
export CODEXK8S_RUN_AGENT_LOGS_RETENTION_DAYS
export CODEXK8S_RUN_INTAKE_LABEL CODEXK8S_RUN_INTAKE_REVISE_LABEL CODEXK8S_RUN_VISION_LABEL CODEXK8S_RUN_VISION_REVISE_LABEL CODEXK8S_RUN_PRD_LABEL CODEXK8S_RUN_PRD_REVISE_LABEL
export CODEXK8S_RUN_ARCH_LABEL CODEXK8S_RUN_ARCH_REVISE_LABEL CODEXK8S_RUN_DESIGN_LABEL CODEXK8S_RUN_DESIGN_REVISE_LABEL CODEXK8S_RUN_PLAN_LABEL CODEXK8S_RUN_PLAN_REVISE_LABEL
export CODEXK8S_RUN_DEV_LABEL CODEXK8S_RUN_DEV_REVISE_LABEL CODEXK8S_RUN_DEBUG_LABEL CODEXK8S_RUN_DOC_AUDIT_LABEL CODEXK8S_RUN_QA_LABEL CODEXK8S_RUN_RELEASE_LABEL
export CODEXK8S_RUN_POSTDEPLOY_LABEL CODEXK8S_RUN_OPS_LABEL CODEXK8S_RUN_SELF_IMPROVE_LABEL CODEXK8S_RUN_RETHINK_LABEL CODEXK8S_MODE_DISCUSSION_LABEL
export CODEXK8S_STATE_BLOCKED_LABEL CODEXK8S_STATE_IN_REVIEW_LABEL CODEXK8S_STATE_APPROVED_LABEL CODEXK8S_STATE_SUPERSEDED_LABEL CODEXK8S_STATE_ABANDONED_LABEL
export CODEXK8S_NEED_INPUT_LABEL CODEXK8S_NEED_PM_LABEL CODEXK8S_NEED_SA_LABEL CODEXK8S_NEED_QA_LABEL CODEXK8S_NEED_SRE_LABEL CODEXK8S_NEED_EM_LABEL CODEXK8S_NEED_KM_LABEL CODEXK8S_NEED_REVIEWER_LABEL
export CODEXK8S_KANIKO_CACHE_ENABLED CODEXK8S_KANIKO_CACHE_REPO CODEXK8S_KANIKO_CACHE_TTL CODEXK8S_KANIKO_CACHE_COMPRESSED CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL
export CODEXK8S_AI_MODEL_GPT_5_3_CODEX_LABEL CODEXK8S_AI_MODEL_GPT_5_3_CODEX_SPARK_LABEL CODEXK8S_AI_MODEL_GPT_5_2_CODEX_LABEL CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MAX_LABEL CODEXK8S_AI_MODEL_GPT_5_2_LABEL CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MINI_LABEL
export CODEXK8S_AI_REASONING_LOW_LABEL CODEXK8S_AI_REASONING_MEDIUM_LABEL CODEXK8S_AI_REASONING_HIGH_LABEL CODEXK8S_AI_REASONING_EXTRA_HIGH_LABEL
bash "${REPO_DIR}/deploy/scripts/deploy_staging.sh"
