-- name: agentsession__upsert :exec
INSERT INTO agent_sessions (
    run_id,
    correlation_id,
    project_id,
    repository_full_name,
    agent_key,
    issue_number,
    branch_name,
    pr_number,
    pr_url,
    trigger_kind,
    template_kind,
    template_source,
    template_locale,
    model,
    reasoning_effort,
    status,
    session_id,
    session_json,
    codex_cli_session_path,
    codex_cli_session_json,
    started_at,
    finished_at,
    updated_at
)
VALUES (
    $1::uuid,
    $2,
    NULLIF($3, '')::uuid,
    $4,
    $5,
    $6,
    NULLIF($7, ''),
    $8,
    NULLIF($9, ''),
    NULLIF($10, ''),
    NULLIF($11, ''),
    NULLIF($12, ''),
    NULLIF($13, ''),
    NULLIF($14, ''),
    NULLIF($15, ''),
    $16,
    NULLIF($17, ''),
    COALESCE($18::jsonb, '{}'::jsonb),
    NULLIF($19, ''),
    $20::jsonb,
    COALESCE($21, NOW()),
    $22,
    NOW()
)
ON CONFLICT (run_id) DO UPDATE
SET correlation_id = EXCLUDED.correlation_id,
    project_id = EXCLUDED.project_id,
    repository_full_name = EXCLUDED.repository_full_name,
    agent_key = EXCLUDED.agent_key,
    issue_number = EXCLUDED.issue_number,
    branch_name = EXCLUDED.branch_name,
    pr_number = EXCLUDED.pr_number,
    pr_url = EXCLUDED.pr_url,
    trigger_kind = EXCLUDED.trigger_kind,
    template_kind = EXCLUDED.template_kind,
    template_source = EXCLUDED.template_source,
    template_locale = EXCLUDED.template_locale,
    model = EXCLUDED.model,
    reasoning_effort = EXCLUDED.reasoning_effort,
    status = EXCLUDED.status,
    session_id = EXCLUDED.session_id,
    session_json = EXCLUDED.session_json,
    codex_cli_session_path = EXCLUDED.codex_cli_session_path,
    codex_cli_session_json = EXCLUDED.codex_cli_session_json,
    started_at = COALESCE(agent_sessions.started_at, EXCLUDED.started_at),
    finished_at = COALESCE(EXCLUDED.finished_at, agent_sessions.finished_at),
    updated_at = NOW();
