#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG_FILE="${ROOT_DIR}/host/config.env"

log() { echo "[$(date -Is)] $*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

escape_squote() {
  printf "%s" "$1" | sed "s/'/'\\''/g"
}

rand_hex() {
  openssl rand -hex "$1" 2>/dev/null || head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

is_ipv4() {
  [[ "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]
}

resolve_ipv4() {
  local host="$1"
  getent ahostsv4 "$host" | awk '{print $1}' | sort -u
}

wait_for_dns_match() {
  local domain="$1"
  local target="$2"
  local timeout_s="$3"
  local interval_s="$4"
  local domain_ips=""
  local target_ips=""
  local deadline=$((SECONDS + timeout_s))

  if is_ipv4 "$target"; then
    target_ips="$target"
  else
    target_ips="$(resolve_ipv4 "$target" || true)"
  fi
  [ -n "$target_ips" ] || die "Unable to resolve target host IPv4: $target"

  while [ "$SECONDS" -lt "$deadline" ]; do
    domain_ips="$(resolve_ipv4 "$domain" || true)"
    if [ -n "$domain_ips" ] && grep -Fxf <(printf '%s\n' "$domain_ips") <(printf '%s\n' "$target_ips") >/dev/null; then
      log "DNS check passed: ${domain} -> $(printf '%s' "$domain_ips" | paste -sd ',' -)"
      return 0
    fi
    log "Waiting DNS: ${domain} should resolve to target host ${target} (timeout in $((deadline - SECONDS))s)"
    sleep "$interval_s"
  done

  die "DNS check failed: ${domain} does not resolve to target host ${target}. Domain IPs='${domain_ips:-<empty>}' Target IPs='${target_ips}'"
}

prompt_if_empty() {
  local var_name="$1"
  local prompt_text="$2"
  local secret="${3:-false}"
  if [ -z "${!var_name:-}" ]; then
    if [ "$secret" = "true" ]; then
      read -r -s -p "$prompt_text: " "$var_name"
      echo
    else
      read -r -p "$prompt_text: " "$var_name"
    fi
  fi
}

require_cmd ssh
require_cmd scp
require_cmd sed
require_cmd getent
require_cmd awk
require_cmd paste
require_cmd sort

if [ -f "$CONFIG_FILE" ]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
fi

prompt_if_empty TARGET_HOST "Target host (IPv4/FQDN)"
prompt_if_empty TARGET_PORT "SSH port"
prompt_if_empty TARGET_ROOT_USER "Root SSH user"
prompt_if_empty TARGET_ROOT_SSH_KEY "Path to root SSH private key"
prompt_if_empty OPERATOR_USER "Operator username"
prompt_if_empty OPERATOR_SSH_PUBKEY_PATH "Path to operator public key"
prompt_if_empty CODEXK8S_GITHUB_REPO "GitHub repo (owner/name)"
prompt_if_empty CODEXK8S_GITHUB_PAT "GitHub fine-grained token" true
prompt_if_empty CODEXK8S_GIT_BOT_TOKEN "CODEXK8S_GIT_BOT_TOKEN (required)" true
prompt_if_empty CODEXK8S_GIT_BOT_USERNAME "CODEXK8S_GIT_BOT_USERNAME"
prompt_if_empty CODEXK8S_GIT_BOT_MAIL "CODEXK8S_GIT_BOT_MAIL"
prompt_if_empty CODEXK8S_PROJECT_DB_ADMIN_HOST "CODEXK8S_PROJECT_DB_ADMIN_HOST (optional; default: postgres)"
prompt_if_empty CODEXK8S_PROJECT_DB_ADMIN_PORT "CODEXK8S_PROJECT_DB_ADMIN_PORT (optional; default: 5432)"
prompt_if_empty CODEXK8S_PROJECT_DB_ADMIN_USER "CODEXK8S_PROJECT_DB_ADMIN_USER (optional; default: CODEXK8S_POSTGRES_USER)"
prompt_if_empty CODEXK8S_PROJECT_DB_ADMIN_PASSWORD "CODEXK8S_PROJECT_DB_ADMIN_PASSWORD (optional; default: CODEXK8S_POSTGRES_PASSWORD)" true
prompt_if_empty CODEXK8S_PROJECT_DB_ADMIN_SSLMODE "CODEXK8S_PROJECT_DB_ADMIN_SSLMODE (optional; default: disable)"
prompt_if_empty CODEXK8S_PROJECT_DB_ADMIN_DATABASE "CODEXK8S_PROJECT_DB_ADMIN_DATABASE (optional; default: postgres)"
prompt_if_empty CODEXK8S_OPENAI_AUTH_FILE "CODEXK8S_OPENAI_AUTH_FILE (optional, one-line JSON from ~/.codex/auth.json)" true
if [ -z "${CODEXK8S_OPENAI_AUTH_FILE:-}" ]; then
  prompt_if_empty CODEXK8S_OPENAI_API_KEY "CODEXK8S_OPENAI_API_KEY (required if CODEXK8S_OPENAI_AUTH_FILE is empty)" true
fi
prompt_if_empty CODEXK8S_BOOTSTRAP_OWNER_EMAIL "CODEXK8S_BOOTSTRAP_OWNER_EMAIL (required)"
prompt_if_empty CODEXK8S_GITHUB_OAUTH_CLIENT_ID "CODEXK8S_GITHUB_OAUTH_CLIENT_ID (required)"
prompt_if_empty CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET "CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET (required)" true
prompt_if_empty CODEXK8S_STAGING_NAMESPACE "Staging namespace"
prompt_if_empty CODEXK8S_STAGING_DOMAIN "Staging domain (required)"
prompt_if_empty CODEXK8S_PUBLIC_BASE_URL "CODEXK8S_PUBLIC_BASE_URL (default: https://<staging-domain>)"
prompt_if_empty CODEXK8S_LETSENCRYPT_EMAIL "Let's Encrypt contact email (required)"

CODEXK8S_ENABLE_GITHUB_RUNNER="${CODEXK8S_ENABLE_GITHUB_RUNNER:-true}"
CODEXK8S_RUNNER_MIN="${CODEXK8S_RUNNER_MIN:-1}"
CODEXK8S_RUNNER_MAX="${CODEXK8S_RUNNER_MAX:-2}"
CODEXK8S_RUNNER_NAMESPACE="${CODEXK8S_RUNNER_NAMESPACE:-actions-runner-staging}"
CODEXK8S_RUNNER_SCALE_SET_NAME="${CODEXK8S_RUNNER_SCALE_SET_NAME:-codex-k8s-ai-staging}"
CODEXK8S_RUNNER_IMAGE="${CODEXK8S_RUNNER_IMAGE:-ghcr.io/actions/actions-runner:latest}"
CODEXK8S_GITHUB_WEBHOOK_URL="${CODEXK8S_GITHUB_WEBHOOK_URL:-https://${CODEXK8S_STAGING_DOMAIN}/api/v1/webhooks/github}"
CODEXK8S_GITHUB_WEBHOOK_EVENTS="${CODEXK8S_GITHUB_WEBHOOK_EVENTS:-push,pull_request,issues,issue_comment,pull_request_review,pull_request_review_comment}"
CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS="${CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS:-}"
CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS="${CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS:-}"
CODEXK8S_GIT_BOT_USERNAME="${CODEXK8S_GIT_BOT_USERNAME:-codex-bot}"
CODEXK8S_GIT_BOT_MAIL="${CODEXK8S_GIT_BOT_MAIL:-codex-bot@codex-k8s.local}"
CODEXK8S_PROJECT_DB_ADMIN_HOST="${CODEXK8S_PROJECT_DB_ADMIN_HOST:-}"
CODEXK8S_PROJECT_DB_ADMIN_PORT="${CODEXK8S_PROJECT_DB_ADMIN_PORT:-}"
CODEXK8S_PROJECT_DB_ADMIN_USER="${CODEXK8S_PROJECT_DB_ADMIN_USER:-}"
CODEXK8S_PROJECT_DB_ADMIN_PASSWORD="${CODEXK8S_PROJECT_DB_ADMIN_PASSWORD:-}"
CODEXK8S_PROJECT_DB_ADMIN_SSLMODE="${CODEXK8S_PROJECT_DB_ADMIN_SSLMODE:-}"
CODEXK8S_PROJECT_DB_ADMIN_DATABASE="${CODEXK8S_PROJECT_DB_ADMIN_DATABASE:-}"
CODEXK8S_OPENAI_API_KEY="${CODEXK8S_OPENAI_API_KEY:-}"
CODEXK8S_OPENAI_AUTH_FILE="${CODEXK8S_OPENAI_AUTH_FILE:-}"
CODEXK8S_RUN_INTAKE_LABEL="${CODEXK8S_RUN_INTAKE_LABEL:-run:intake}"
CODEXK8S_RUN_INTAKE_REVISE_LABEL="${CODEXK8S_RUN_INTAKE_REVISE_LABEL:-run:intake:revise}"
CODEXK8S_RUN_VISION_LABEL="${CODEXK8S_RUN_VISION_LABEL:-run:vision}"
CODEXK8S_RUN_VISION_REVISE_LABEL="${CODEXK8S_RUN_VISION_REVISE_LABEL:-run:vision:revise}"
CODEXK8S_RUN_PRD_LABEL="${CODEXK8S_RUN_PRD_LABEL:-run:prd}"
CODEXK8S_RUN_PRD_REVISE_LABEL="${CODEXK8S_RUN_PRD_REVISE_LABEL:-run:prd:revise}"
CODEXK8S_RUN_ARCH_LABEL="${CODEXK8S_RUN_ARCH_LABEL:-run:arch}"
CODEXK8S_RUN_ARCH_REVISE_LABEL="${CODEXK8S_RUN_ARCH_REVISE_LABEL:-run:arch:revise}"
CODEXK8S_RUN_DESIGN_LABEL="${CODEXK8S_RUN_DESIGN_LABEL:-run:design}"
CODEXK8S_RUN_DESIGN_REVISE_LABEL="${CODEXK8S_RUN_DESIGN_REVISE_LABEL:-run:design:revise}"
CODEXK8S_RUN_PLAN_LABEL="${CODEXK8S_RUN_PLAN_LABEL:-run:plan}"
CODEXK8S_RUN_PLAN_REVISE_LABEL="${CODEXK8S_RUN_PLAN_REVISE_LABEL:-run:plan:revise}"
CODEXK8S_RUN_DEV_LABEL="${CODEXK8S_RUN_DEV_LABEL:-run:dev}"
CODEXK8S_RUN_DEV_REVISE_LABEL="${CODEXK8S_RUN_DEV_REVISE_LABEL:-run:dev:revise}"
CODEXK8S_RUN_DEBUG_LABEL="${CODEXK8S_RUN_DEBUG_LABEL:-run:debug}"
CODEXK8S_RUN_DOC_AUDIT_LABEL="${CODEXK8S_RUN_DOC_AUDIT_LABEL:-run:doc-audit}"
CODEXK8S_RUN_QA_LABEL="${CODEXK8S_RUN_QA_LABEL:-run:qa}"
CODEXK8S_RUN_RELEASE_LABEL="${CODEXK8S_RUN_RELEASE_LABEL:-run:release}"
CODEXK8S_RUN_POSTDEPLOY_LABEL="${CODEXK8S_RUN_POSTDEPLOY_LABEL:-run:postdeploy}"
CODEXK8S_RUN_OPS_LABEL="${CODEXK8S_RUN_OPS_LABEL:-run:ops}"
CODEXK8S_RUN_SELF_IMPROVE_LABEL="${CODEXK8S_RUN_SELF_IMPROVE_LABEL:-run:self-improve}"
CODEXK8S_RUN_ABORT_LABEL="${CODEXK8S_RUN_ABORT_LABEL:-run:abort}"
CODEXK8S_RUN_RETHINK_LABEL="${CODEXK8S_RUN_RETHINK_LABEL:-run:rethink}"
CODEXK8S_MODE_DISCUSSION_LABEL="${CODEXK8S_MODE_DISCUSSION_LABEL:-mode:discussion}"
CODEXK8S_STATE_BLOCKED_LABEL="${CODEXK8S_STATE_BLOCKED_LABEL:-state:blocked}"
CODEXK8S_STATE_IN_REVIEW_LABEL="${CODEXK8S_STATE_IN_REVIEW_LABEL:-state:in-review}"
CODEXK8S_STATE_APPROVED_LABEL="${CODEXK8S_STATE_APPROVED_LABEL:-state:approved}"
CODEXK8S_STATE_SUPERSEDED_LABEL="${CODEXK8S_STATE_SUPERSEDED_LABEL:-state:superseded}"
CODEXK8S_STATE_ABANDONED_LABEL="${CODEXK8S_STATE_ABANDONED_LABEL:-state:abandoned}"
CODEXK8S_NEED_INPUT_LABEL="${CODEXK8S_NEED_INPUT_LABEL:-need:input}"
CODEXK8S_NEED_PM_LABEL="${CODEXK8S_NEED_PM_LABEL:-need:pm}"
CODEXK8S_NEED_SA_LABEL="${CODEXK8S_NEED_SA_LABEL:-need:sa}"
CODEXK8S_NEED_QA_LABEL="${CODEXK8S_NEED_QA_LABEL:-need:qa}"
CODEXK8S_NEED_SRE_LABEL="${CODEXK8S_NEED_SRE_LABEL:-need:sre}"
CODEXK8S_NEED_EM_LABEL="${CODEXK8S_NEED_EM_LABEL:-need:em}"
CODEXK8S_NEED_KM_LABEL="${CODEXK8S_NEED_KM_LABEL:-need:km}"
CODEXK8S_NEED_REVIEWER_LABEL="${CODEXK8S_NEED_REVIEWER_LABEL:-need:reviewer}"
CODEXK8S_AI_MODEL_GPT_5_3_CODEX_LABEL="${CODEXK8S_AI_MODEL_GPT_5_3_CODEX_LABEL:-[ai-model-gpt-5.3-codex]}"
CODEXK8S_AI_MODEL_GPT_5_3_CODEX_SPARK_LABEL="${CODEXK8S_AI_MODEL_GPT_5_3_CODEX_SPARK_LABEL:-[ai-model-gpt-5.3-codex-spark]}"
CODEXK8S_AI_MODEL_GPT_5_2_CODEX_LABEL="${CODEXK8S_AI_MODEL_GPT_5_2_CODEX_LABEL:-[ai-model-gpt-5.2-codex]}"
CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MAX_LABEL="${CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MAX_LABEL:-[ai-model-gpt-5.1-codex-max]}"
CODEXK8S_AI_MODEL_GPT_5_2_LABEL="${CODEXK8S_AI_MODEL_GPT_5_2_LABEL:-[ai-model-gpt-5.2]}"
CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MINI_LABEL="${CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MINI_LABEL:-[ai-model-gpt-5.1-codex-mini]}"
CODEXK8S_AI_REASONING_LOW_LABEL="${CODEXK8S_AI_REASONING_LOW_LABEL:-[ai-reasoning-low]}"
CODEXK8S_AI_REASONING_MEDIUM_LABEL="${CODEXK8S_AI_REASONING_MEDIUM_LABEL:-[ai-reasoning-medium]}"
CODEXK8S_AI_REASONING_HIGH_LABEL="${CODEXK8S_AI_REASONING_HIGH_LABEL:-[ai-reasoning-high]}"
CODEXK8S_AI_REASONING_EXTRA_HIGH_LABEL="${CODEXK8S_AI_REASONING_EXTRA_HIGH_LABEL:-[ai-reasoning-extra-high]}"
CODEXK8S_INTERNAL_REGISTRY_SERVICE="${CODEXK8S_INTERNAL_REGISTRY_SERVICE:-codex-k8s-registry}"
CODEXK8S_INTERNAL_REGISTRY_PORT="${CODEXK8S_INTERNAL_REGISTRY_PORT:-5000}"
CODEXK8S_INTERNAL_REGISTRY_STORAGE_SIZE="${CODEXK8S_INTERNAL_REGISTRY_STORAGE_SIZE:-20Gi}"
CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/api-gateway}"
CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/control-plane}"
CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/worker}"
CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/agent-runner}"
CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY="${CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY:-codex-k8s/web-console}"
CODEXK8S_INTERNAL_REGISTRY_HOST="${CODEXK8S_INTERNAL_REGISTRY_HOST:-127.0.0.1:${CODEXK8S_INTERNAL_REGISTRY_PORT}}"
CODEXK8S_INSTALL_LONGHORN="${CODEXK8S_INSTALL_LONGHORN:-false}"
CODEXK8S_WORKER_REPLICAS="${CODEXK8S_WORKER_REPLICAS:-1}"
CODEXK8S_WORKER_POLL_INTERVAL="${CODEXK8S_WORKER_POLL_INTERVAL:-5s}"
CODEXK8S_WORKER_CLAIM_LIMIT="${CODEXK8S_WORKER_CLAIM_LIMIT:-2}"
CODEXK8S_WORKER_RUNNING_CHECK_LIMIT="${CODEXK8S_WORKER_RUNNING_CHECK_LIMIT:-200}"
CODEXK8S_WORKER_SLOTS_PER_PROJECT="${CODEXK8S_WORKER_SLOTS_PER_PROJECT:-2}"
CODEXK8S_WORKER_SLOT_LEASE_TTL="${CODEXK8S_WORKER_SLOT_LEASE_TTL:-10m}"
CODEXK8S_INGRESS_HOST_NETWORK="${CODEXK8S_INGRESS_HOST_NETWORK:-true}"
CODEXK8S_FIREWALL_ENABLED="${CODEXK8S_FIREWALL_ENABLED:-true}"
CODEXK8S_NETWORK_POLICY_BASELINE="${CODEXK8S_NETWORK_POLICY_BASELINE:-true}"
CODEXK8S_PLATFORM_MCP_PORT="${CODEXK8S_PLATFORM_MCP_PORT:-8081}"
CODEXK8S_K8S_API_CIDR="${CODEXK8S_K8S_API_CIDR:-}"
CODEXK8S_K8S_API_PORT="${CODEXK8S_K8S_API_PORT:-6443}"
CODEXK8S_DNS_WAIT_TIMEOUT="${CODEXK8S_DNS_WAIT_TIMEOUT:-900}"
CODEXK8S_DNS_WAIT_INTERVAL="${CODEXK8S_DNS_WAIT_INTERVAL:-10}"
CODEXK8S_NODE_DISCOVERY_TIMEOUT="${CODEXK8S_NODE_DISCOVERY_TIMEOUT:-300}"
CODEXK8S_NODE_READY_TIMEOUT="${CODEXK8S_NODE_READY_TIMEOUT:-1200s}"
CODEXK8S_INGRESS_READY_TIMEOUT="${CODEXK8S_INGRESS_READY_TIMEOUT:-1200s}"
CODEXK8S_CERT_MANAGER_READY_TIMEOUT="${CODEXK8S_CERT_MANAGER_READY_TIMEOUT:-1200s}"
CODEXK8S_HELM_TIMEOUT="${CODEXK8S_HELM_TIMEOUT:-20m}"
CODEXK8S_ROLLOUT_TIMEOUT="${CODEXK8S_ROLLOUT_TIMEOUT:-1800s}"
CODEXK8S_WAIT_ROLLOUT="${CODEXK8S_WAIT_ROLLOUT:-true}"
CODEXK8S_LETSENCRYPT_SERVER="${CODEXK8S_LETSENCRYPT_SERVER:-https://acme-v02.api.letsencrypt.org/directory}"
CODEXK8S_KANIKO_TIMEOUT="${CODEXK8S_KANIKO_TIMEOUT:-1800s}"
CODEXK8S_KANIKO_CACHE_ENABLED="${CODEXK8S_KANIKO_CACHE_ENABLED:-true}"
CODEXK8S_KANIKO_CACHE_REPO="${CODEXK8S_KANIKO_CACHE_REPO:-}"
CODEXK8S_KANIKO_CACHE_TTL="${CODEXK8S_KANIKO_CACHE_TTL:-168h}"
CODEXK8S_KANIKO_CACHE_COMPRESSED="${CODEXK8S_KANIKO_CACHE_COMPRESSED:-false}"
CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL="${CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL:-4}"
TARGET_PORT="${TARGET_PORT:-22}"
TARGET_ROOT_USER="${TARGET_ROOT_USER:-root}"
CODEXK8S_LEARNING_MODE_DEFAULT="${CODEXK8S_LEARNING_MODE_DEFAULT-true}"
CODEXK8S_SSH_PORT="${CODEXK8S_SSH_PORT:-$TARGET_PORT}"
CODEXK8S_API_GATEWAY_IMAGE="${CODEXK8S_API_GATEWAY_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_CONTROL_PLANE_IMAGE="${CODEXK8S_CONTROL_PLANE_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_WORKER_IMAGE="${CODEXK8S_WORKER_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_AGENT_RUNNER_IMAGE="${CODEXK8S_AGENT_RUNNER_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_WEB_CONSOLE_IMAGE="${CODEXK8S_WEB_CONSOLE_IMAGE:-${CODEXK8S_INTERNAL_REGISTRY_HOST}/${CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY}:latest}"
CODEXK8S_WORKER_K8S_NAMESPACE="${CODEXK8S_WORKER_K8S_NAMESPACE:-$CODEXK8S_STAGING_NAMESPACE}"
CODEXK8S_WORKER_JOB_IMAGE="${CODEXK8S_WORKER_JOB_IMAGE:-$CODEXK8S_AGENT_RUNNER_IMAGE}"
CODEXK8S_WORKER_JOB_COMMAND="${CODEXK8S_WORKER_JOB_COMMAND:-/usr/local/bin/codex-k8s-agent-runner}"
CODEXK8S_WORKER_JOB_TTL_SECONDS="${CODEXK8S_WORKER_JOB_TTL_SECONDS:-600}"
CODEXK8S_WORKER_JOB_BACKOFF_LIMIT="${CODEXK8S_WORKER_JOB_BACKOFF_LIMIT:-0}"
CODEXK8S_WORKER_JOB_ACTIVE_DEADLINE_SECONDS="${CODEXK8S_WORKER_JOB_ACTIVE_DEADLINE_SECONDS:-900}"
CODEXK8S_WORKER_RUN_NAMESPACE_PREFIX="${CODEXK8S_WORKER_RUN_NAMESPACE_PREFIX:-codex-issue}"
CODEXK8S_WORKER_RUN_NAMESPACE_CLEANUP="${CODEXK8S_WORKER_RUN_NAMESPACE_CLEANUP:-true}"
CODEXK8S_WORKER_RUN_SERVICE_ACCOUNT="${CODEXK8S_WORKER_RUN_SERVICE_ACCOUNT:-codex-runner}"
CODEXK8S_WORKER_RUN_ROLE_NAME="${CODEXK8S_WORKER_RUN_ROLE_NAME:-codex-runner}"
CODEXK8S_WORKER_RUN_ROLE_BINDING_NAME="${CODEXK8S_WORKER_RUN_ROLE_BINDING_NAME:-codex-runner}"
CODEXK8S_WORKER_RUN_RESOURCE_QUOTA_NAME="${CODEXK8S_WORKER_RUN_RESOURCE_QUOTA_NAME:-codex-run-quota}"
CODEXK8S_WORKER_RUN_LIMIT_RANGE_NAME="${CODEXK8S_WORKER_RUN_LIMIT_RANGE_NAME:-codex-run-limits}"
CODEXK8S_WORKER_RUN_CREDENTIALS_SECRET_NAME="${CODEXK8S_WORKER_RUN_CREDENTIALS_SECRET_NAME:-codex-run-credentials}"
CODEXK8S_WORKER_RUN_QUOTA_PODS="${CODEXK8S_WORKER_RUN_QUOTA_PODS:-20}"
CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_CPU="${CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_CPU:-6}"
CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_MEMORY="${CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_MEMORY:-24Gi}"
CODEXK8S_WORKER_RUN_QUOTA_LIMITS_CPU="${CODEXK8S_WORKER_RUN_QUOTA_LIMITS_CPU:-8}"
CODEXK8S_WORKER_RUN_QUOTA_LIMITS_MEMORY="${CODEXK8S_WORKER_RUN_QUOTA_LIMITS_MEMORY:-32Gi}"
CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_CPU="${CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_CPU:-4}"
CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_MEMORY="${CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_MEMORY:-16Gi}"
CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_CPU="${CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_CPU:-6}"
CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_MEMORY="${CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_MEMORY:-24Gi}"
if [ -z "${CODEXK8S_AGENT_DEFAULT_MODEL:-}" ]; then
  if [ -n "${CODEXK8S_OPENAI_AUTH_FILE}" ]; then
    CODEXK8S_AGENT_DEFAULT_MODEL="gpt-5.3-codex"
  else
    CODEXK8S_AGENT_DEFAULT_MODEL="gpt-5.2-codex"
  fi
fi
CODEXK8S_AGENT_DEFAULT_REASONING_EFFORT="${CODEXK8S_AGENT_DEFAULT_REASONING_EFFORT:-high}"
CODEXK8S_AGENT_DEFAULT_LOCALE="${CODEXK8S_AGENT_DEFAULT_LOCALE:-ru}"
CODEXK8S_AGENT_BASE_BRANCH="${CODEXK8S_AGENT_BASE_BRANCH:-main}"
CODEXK8S_CONTROL_PLANE_GRPC_TARGET="${CODEXK8S_CONTROL_PLANE_GRPC_TARGET:-codex-k8s-control-plane.${CODEXK8S_STAGING_NAMESPACE}.svc.cluster.local:9090}"
CODEXK8S_CONTROL_PLANE_MCP_BASE_URL="${CODEXK8S_CONTROL_PLANE_MCP_BASE_URL:-http://codex-k8s-control-plane.${CODEXK8S_STAGING_NAMESPACE}.svc.cluster.local:8081/mcp}"
CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_CPU="${CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_CPU:-100m}"
CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_MEMORY="${CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_MEMORY:-256Mi}"
CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_CPU="${CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_CPU:-1000m}"
CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_MEMORY="${CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_MEMORY:-1Gi}"
CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_CPU="${CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_CPU:-100m}"
CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_MEMORY="${CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_MEMORY:-256Mi}"
CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_CPU="${CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_CPU:-1000m}"
CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_MEMORY="${CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_MEMORY:-1Gi}"
CODEXK8S_WORKER_RESOURCES_REQUEST_CPU="${CODEXK8S_WORKER_RESOURCES_REQUEST_CPU:-100m}"
CODEXK8S_WORKER_RESOURCES_REQUEST_MEMORY="${CODEXK8S_WORKER_RESOURCES_REQUEST_MEMORY:-256Mi}"
CODEXK8S_WORKER_RESOURCES_LIMIT_CPU="${CODEXK8S_WORKER_RESOURCES_LIMIT_CPU:-1000m}"
CODEXK8S_WORKER_RESOURCES_LIMIT_MEMORY="${CODEXK8S_WORKER_RESOURCES_LIMIT_MEMORY:-1Gi}"
CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_CPU="${CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_CPU:-100m}"
CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_MEMORY="${CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_MEMORY:-128Mi}"
CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_CPU="${CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_CPU:-500m}"
CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_MEMORY="${CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_MEMORY:-512Mi}"
CODEXK8S_KANIKO_RESOURCES_REQUEST_CPU="${CODEXK8S_KANIKO_RESOURCES_REQUEST_CPU:-8}"
CODEXK8S_KANIKO_RESOURCES_REQUEST_MEMORY="${CODEXK8S_KANIKO_RESOURCES_REQUEST_MEMORY:-16Gi}"
CODEXK8S_KANIKO_RESOURCES_LIMIT_CPU="${CODEXK8S_KANIKO_RESOURCES_LIMIT_CPU:-16}"
CODEXK8S_KANIKO_RESOURCES_LIMIT_MEMORY="${CODEXK8S_KANIKO_RESOURCES_LIMIT_MEMORY:-32Gi}"
CODEXK8S_PUBLIC_BASE_URL="${CODEXK8S_PUBLIC_BASE_URL:-}"
CODEXK8S_JWT_TTL="${CODEXK8S_JWT_TTL:-15m}"
CODEXK8S_MCP_TOKEN_TTL="${CODEXK8S_MCP_TOKEN_TTL:-24h}"
CODEXK8S_RUN_AGENT_LOGS_RETENTION_DAYS="${CODEXK8S_RUN_AGENT_LOGS_RETENTION_DAYS:-14}"

[ -f "$TARGET_ROOT_SSH_KEY" ] || die "SSH private key not found: $TARGET_ROOT_SSH_KEY"
[ -f "$OPERATOR_SSH_PUBKEY_PATH" ] || die "Operator public key not found: $OPERATOR_SSH_PUBKEY_PATH"
OPERATOR_SSH_PUBKEY="$(cat "$OPERATOR_SSH_PUBKEY_PATH")"

[ -n "${CODEXK8S_STAGING_DOMAIN:-}" ] || die "CODEXK8S_STAGING_DOMAIN is required"
[ -n "${CODEXK8S_LETSENCRYPT_EMAIL:-}" ] || die "CODEXK8S_LETSENCRYPT_EMAIL is required"
[ -n "${CODEXK8S_GIT_BOT_TOKEN:-}" ] || die "CODEXK8S_GIT_BOT_TOKEN is required"
if [ -z "${CODEXK8S_OPENAI_API_KEY:-}" ] && [ -z "${CODEXK8S_OPENAI_AUTH_FILE:-}" ]; then
  die "Either CODEXK8S_OPENAI_API_KEY or CODEXK8S_OPENAI_AUTH_FILE is required"
fi
case "$CODEXK8S_DNS_WAIT_TIMEOUT" in
  ''|*[!0-9]*) die "CODEXK8S_DNS_WAIT_TIMEOUT must be integer seconds";;
esac
case "$CODEXK8S_DNS_WAIT_INTERVAL" in
  ''|*[!0-9]*) die "CODEXK8S_DNS_WAIT_INTERVAL must be integer seconds";;
esac
wait_for_dns_match "$CODEXK8S_STAGING_DOMAIN" "$TARGET_HOST" "$CODEXK8S_DNS_WAIT_TIMEOUT" "$CODEXK8S_DNS_WAIT_INTERVAL"

if [ -z "$CODEXK8S_PUBLIC_BASE_URL" ]; then
  CODEXK8S_PUBLIC_BASE_URL="https://${CODEXK8S_STAGING_DOMAIN}"
fi

if [ -z "$CODEXK8S_K8S_API_CIDR" ]; then
  if is_ipv4 "$TARGET_HOST"; then
    CODEXK8S_K8S_API_CIDR="${TARGET_HOST}/32"
  else
    resolved_ip="$(resolve_ipv4 "$TARGET_HOST" | head -n1 || true)"
    [ -n "$resolved_ip" ] || die "Unable to resolve TARGET_HOST IPv4 for CODEXK8S_K8S_API_CIDR: $TARGET_HOST"
    CODEXK8S_K8S_API_CIDR="${resolved_ip}/32"
  fi
fi

CODEXK8S_POSTGRES_DB="codex_k8s"
CODEXK8S_POSTGRES_USER="codex_k8s"
CODEXK8S_POSTGRES_PASSWORD="$(rand_hex 24)"
CODEXK8S_APP_SECRET_KEY="$(rand_hex 32)"
CODEXK8S_TOKEN_ENCRYPTION_KEY="$(rand_hex 32)"
CODEXK8S_MCP_TOKEN_SIGNING_KEY="${CODEXK8S_MCP_TOKEN_SIGNING_KEY:-$(rand_hex 32)}"
CODEXK8S_JWT_SIGNING_KEY="${CODEXK8S_JWT_SIGNING_KEY:-$(rand_hex 32)}"
CODEXK8S_GITHUB_WEBHOOK_SECRET="${CODEXK8S_GITHUB_WEBHOOK_SECRET:-$(rand_hex 32)}"
CODEXK8S_PROJECT_DB_ADMIN_HOST="${CODEXK8S_PROJECT_DB_ADMIN_HOST:-postgres}"
CODEXK8S_PROJECT_DB_ADMIN_PORT="${CODEXK8S_PROJECT_DB_ADMIN_PORT:-5432}"
CODEXK8S_PROJECT_DB_ADMIN_USER="${CODEXK8S_PROJECT_DB_ADMIN_USER:-$CODEXK8S_POSTGRES_USER}"
CODEXK8S_PROJECT_DB_ADMIN_PASSWORD="${CODEXK8S_PROJECT_DB_ADMIN_PASSWORD:-$CODEXK8S_POSTGRES_PASSWORD}"
CODEXK8S_PROJECT_DB_ADMIN_SSLMODE="${CODEXK8S_PROJECT_DB_ADMIN_SSLMODE:-disable}"
CODEXK8S_PROJECT_DB_ADMIN_DATABASE="${CODEXK8S_PROJECT_DB_ADMIN_DATABASE:-postgres}"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

REMOTE_DIR="/root/codex-k8s-bootstrap"
REMOTE_ENV="${REMOTE_DIR}/bootstrap.env"

cat > "${TMP_DIR}/bootstrap.env" <<ENV
OPERATOR_USER='$(escape_squote "$OPERATOR_USER")'
OPERATOR_SSH_PUBKEY='$(escape_squote "$OPERATOR_SSH_PUBKEY")'
CODEXK8S_GITHUB_REPO='$(escape_squote "$CODEXK8S_GITHUB_REPO")'
CODEXK8S_GITHUB_PAT='$(escape_squote "$CODEXK8S_GITHUB_PAT")'
CODEXK8S_GIT_BOT_TOKEN='$(escape_squote "$CODEXK8S_GIT_BOT_TOKEN")'
CODEXK8S_GIT_BOT_USERNAME='$(escape_squote "$CODEXK8S_GIT_BOT_USERNAME")'
CODEXK8S_GIT_BOT_MAIL='$(escape_squote "$CODEXK8S_GIT_BOT_MAIL")'
CODEXK8S_OPENAI_API_KEY='$(escape_squote "$CODEXK8S_OPENAI_API_KEY")'
CODEXK8S_OPENAI_AUTH_FILE='$(escape_squote "${CODEXK8S_OPENAI_AUTH_FILE:-}")'
CODEXK8S_CONTEXT7_API_KEY='$(escape_squote "${CODEXK8S_CONTEXT7_API_KEY:-}")'
CODEXK8S_PUBLIC_BASE_URL='$(escape_squote "$CODEXK8S_PUBLIC_BASE_URL")'
CODEXK8S_BOOTSTRAP_OWNER_EMAIL='$(escape_squote "$CODEXK8S_BOOTSTRAP_OWNER_EMAIL")'
CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS='$(escape_squote "${CODEXK8S_BOOTSTRAP_ALLOWED_EMAILS:-}")'
CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS='$(escape_squote "${CODEXK8S_BOOTSTRAP_PLATFORM_ADMIN_EMAILS:-}")'
CODEXK8S_GITHUB_OAUTH_CLIENT_ID='$(escape_squote "$CODEXK8S_GITHUB_OAUTH_CLIENT_ID")'
CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET='$(escape_squote "$CODEXK8S_GITHUB_OAUTH_CLIENT_SECRET")'
CODEXK8S_JWT_SIGNING_KEY='$(escape_squote "$CODEXK8S_JWT_SIGNING_KEY")'
CODEXK8S_JWT_TTL='$(escape_squote "$CODEXK8S_JWT_TTL")'
CODEXK8S_MCP_TOKEN_SIGNING_KEY='$(escape_squote "$CODEXK8S_MCP_TOKEN_SIGNING_KEY")'
CODEXK8S_MCP_TOKEN_TTL='$(escape_squote "$CODEXK8S_MCP_TOKEN_TTL")'
CODEXK8S_RUN_AGENT_LOGS_RETENTION_DAYS='$(escape_squote "$CODEXK8S_RUN_AGENT_LOGS_RETENTION_DAYS")'
CODEXK8S_STAGING_NAMESPACE='$(escape_squote "$CODEXK8S_STAGING_NAMESPACE")'
CODEXK8S_STAGING_DOMAIN='$(escape_squote "$CODEXK8S_STAGING_DOMAIN")'
CODEXK8S_LETSENCRYPT_EMAIL='$(escape_squote "$CODEXK8S_LETSENCRYPT_EMAIL")'
CODEXK8S_LETSENCRYPT_SERVER='$(escape_squote "$CODEXK8S_LETSENCRYPT_SERVER")'
CODEXK8S_API_GATEWAY_IMAGE='$(escape_squote "$CODEXK8S_API_GATEWAY_IMAGE")'
CODEXK8S_CONTROL_PLANE_IMAGE='$(escape_squote "$CODEXK8S_CONTROL_PLANE_IMAGE")'
CODEXK8S_WORKER_IMAGE='$(escape_squote "$CODEXK8S_WORKER_IMAGE")'
CODEXK8S_AGENT_RUNNER_IMAGE='$(escape_squote "$CODEXK8S_AGENT_RUNNER_IMAGE")'
CODEXK8S_WEB_CONSOLE_IMAGE='$(escape_squote "$CODEXK8S_WEB_CONSOLE_IMAGE")'
CODEXK8S_ENABLE_GITHUB_RUNNER='$(escape_squote "$CODEXK8S_ENABLE_GITHUB_RUNNER")'
CODEXK8S_RUNNER_MIN='$(escape_squote "$CODEXK8S_RUNNER_MIN")'
CODEXK8S_RUNNER_MAX='$(escape_squote "$CODEXK8S_RUNNER_MAX")'
CODEXK8S_RUNNER_NAMESPACE='$(escape_squote "$CODEXK8S_RUNNER_NAMESPACE")'
CODEXK8S_RUNNER_SCALE_SET_NAME='$(escape_squote "$CODEXK8S_RUNNER_SCALE_SET_NAME")'
CODEXK8S_RUNNER_IMAGE='$(escape_squote "$CODEXK8S_RUNNER_IMAGE")'
CODEXK8S_GITHUB_WEBHOOK_URL='$(escape_squote "$CODEXK8S_GITHUB_WEBHOOK_URL")'
CODEXK8S_GITHUB_WEBHOOK_EVENTS='$(escape_squote "$CODEXK8S_GITHUB_WEBHOOK_EVENTS")'
CODEXK8S_RUN_INTAKE_LABEL='$(escape_squote "$CODEXK8S_RUN_INTAKE_LABEL")'
CODEXK8S_RUN_INTAKE_REVISE_LABEL='$(escape_squote "$CODEXK8S_RUN_INTAKE_REVISE_LABEL")'
CODEXK8S_RUN_VISION_LABEL='$(escape_squote "$CODEXK8S_RUN_VISION_LABEL")'
CODEXK8S_RUN_VISION_REVISE_LABEL='$(escape_squote "$CODEXK8S_RUN_VISION_REVISE_LABEL")'
CODEXK8S_RUN_PRD_LABEL='$(escape_squote "$CODEXK8S_RUN_PRD_LABEL")'
CODEXK8S_RUN_PRD_REVISE_LABEL='$(escape_squote "$CODEXK8S_RUN_PRD_REVISE_LABEL")'
CODEXK8S_RUN_ARCH_LABEL='$(escape_squote "$CODEXK8S_RUN_ARCH_LABEL")'
CODEXK8S_RUN_ARCH_REVISE_LABEL='$(escape_squote "$CODEXK8S_RUN_ARCH_REVISE_LABEL")'
CODEXK8S_RUN_DESIGN_LABEL='$(escape_squote "$CODEXK8S_RUN_DESIGN_LABEL")'
CODEXK8S_RUN_DESIGN_REVISE_LABEL='$(escape_squote "$CODEXK8S_RUN_DESIGN_REVISE_LABEL")'
CODEXK8S_RUN_PLAN_LABEL='$(escape_squote "$CODEXK8S_RUN_PLAN_LABEL")'
CODEXK8S_RUN_PLAN_REVISE_LABEL='$(escape_squote "$CODEXK8S_RUN_PLAN_REVISE_LABEL")'
CODEXK8S_RUN_DEV_LABEL='$(escape_squote "$CODEXK8S_RUN_DEV_LABEL")'
CODEXK8S_RUN_DEV_REVISE_LABEL='$(escape_squote "$CODEXK8S_RUN_DEV_REVISE_LABEL")'
CODEXK8S_RUN_DEBUG_LABEL='$(escape_squote "$CODEXK8S_RUN_DEBUG_LABEL")'
CODEXK8S_RUN_DOC_AUDIT_LABEL='$(escape_squote "$CODEXK8S_RUN_DOC_AUDIT_LABEL")'
CODEXK8S_RUN_QA_LABEL='$(escape_squote "$CODEXK8S_RUN_QA_LABEL")'
CODEXK8S_RUN_RELEASE_LABEL='$(escape_squote "$CODEXK8S_RUN_RELEASE_LABEL")'
CODEXK8S_RUN_POSTDEPLOY_LABEL='$(escape_squote "$CODEXK8S_RUN_POSTDEPLOY_LABEL")'
CODEXK8S_RUN_OPS_LABEL='$(escape_squote "$CODEXK8S_RUN_OPS_LABEL")'
CODEXK8S_RUN_SELF_IMPROVE_LABEL='$(escape_squote "$CODEXK8S_RUN_SELF_IMPROVE_LABEL")'
CODEXK8S_RUN_ABORT_LABEL='$(escape_squote "$CODEXK8S_RUN_ABORT_LABEL")'
CODEXK8S_RUN_RETHINK_LABEL='$(escape_squote "$CODEXK8S_RUN_RETHINK_LABEL")'
CODEXK8S_MODE_DISCUSSION_LABEL='$(escape_squote "$CODEXK8S_MODE_DISCUSSION_LABEL")'
CODEXK8S_STATE_BLOCKED_LABEL='$(escape_squote "$CODEXK8S_STATE_BLOCKED_LABEL")'
CODEXK8S_STATE_IN_REVIEW_LABEL='$(escape_squote "$CODEXK8S_STATE_IN_REVIEW_LABEL")'
CODEXK8S_STATE_APPROVED_LABEL='$(escape_squote "$CODEXK8S_STATE_APPROVED_LABEL")'
CODEXK8S_STATE_SUPERSEDED_LABEL='$(escape_squote "$CODEXK8S_STATE_SUPERSEDED_LABEL")'
CODEXK8S_STATE_ABANDONED_LABEL='$(escape_squote "$CODEXK8S_STATE_ABANDONED_LABEL")'
CODEXK8S_NEED_INPUT_LABEL='$(escape_squote "$CODEXK8S_NEED_INPUT_LABEL")'
CODEXK8S_NEED_PM_LABEL='$(escape_squote "$CODEXK8S_NEED_PM_LABEL")'
CODEXK8S_NEED_SA_LABEL='$(escape_squote "$CODEXK8S_NEED_SA_LABEL")'
CODEXK8S_NEED_QA_LABEL='$(escape_squote "$CODEXK8S_NEED_QA_LABEL")'
CODEXK8S_NEED_SRE_LABEL='$(escape_squote "$CODEXK8S_NEED_SRE_LABEL")'
CODEXK8S_NEED_EM_LABEL='$(escape_squote "$CODEXK8S_NEED_EM_LABEL")'
CODEXK8S_NEED_KM_LABEL='$(escape_squote "$CODEXK8S_NEED_KM_LABEL")'
CODEXK8S_NEED_REVIEWER_LABEL='$(escape_squote "$CODEXK8S_NEED_REVIEWER_LABEL")'
CODEXK8S_AI_MODEL_GPT_5_3_CODEX_LABEL='$(escape_squote "$CODEXK8S_AI_MODEL_GPT_5_3_CODEX_LABEL")'
CODEXK8S_AI_MODEL_GPT_5_3_CODEX_SPARK_LABEL='$(escape_squote "$CODEXK8S_AI_MODEL_GPT_5_3_CODEX_SPARK_LABEL")'
CODEXK8S_AI_MODEL_GPT_5_2_CODEX_LABEL='$(escape_squote "$CODEXK8S_AI_MODEL_GPT_5_2_CODEX_LABEL")'
CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MAX_LABEL='$(escape_squote "$CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MAX_LABEL")'
CODEXK8S_AI_MODEL_GPT_5_2_LABEL='$(escape_squote "$CODEXK8S_AI_MODEL_GPT_5_2_LABEL")'
CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MINI_LABEL='$(escape_squote "$CODEXK8S_AI_MODEL_GPT_5_1_CODEX_MINI_LABEL")'
CODEXK8S_AI_REASONING_LOW_LABEL='$(escape_squote "$CODEXK8S_AI_REASONING_LOW_LABEL")'
CODEXK8S_AI_REASONING_MEDIUM_LABEL='$(escape_squote "$CODEXK8S_AI_REASONING_MEDIUM_LABEL")'
CODEXK8S_AI_REASONING_HIGH_LABEL='$(escape_squote "$CODEXK8S_AI_REASONING_HIGH_LABEL")'
CODEXK8S_AI_REASONING_EXTRA_HIGH_LABEL='$(escape_squote "$CODEXK8S_AI_REASONING_EXTRA_HIGH_LABEL")'
CODEXK8S_INTERNAL_REGISTRY_SERVICE='$(escape_squote "$CODEXK8S_INTERNAL_REGISTRY_SERVICE")'
CODEXK8S_INTERNAL_REGISTRY_PORT='$(escape_squote "$CODEXK8S_INTERNAL_REGISTRY_PORT")'
CODEXK8S_INTERNAL_REGISTRY_STORAGE_SIZE='$(escape_squote "$CODEXK8S_INTERNAL_REGISTRY_STORAGE_SIZE")'
CODEXK8S_INTERNAL_REGISTRY_HOST='$(escape_squote "$CODEXK8S_INTERNAL_REGISTRY_HOST")'
CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY='$(escape_squote "$CODEXK8S_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY")'
CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY='$(escape_squote "$CODEXK8S_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY")'
CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY='$(escape_squote "$CODEXK8S_WORKER_INTERNAL_IMAGE_REPOSITORY")'
CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY='$(escape_squote "$CODEXK8S_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY")'
CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY='$(escape_squote "$CODEXK8S_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY")'
CODEXK8S_INSTALL_LONGHORN='$(escape_squote "$CODEXK8S_INSTALL_LONGHORN")'
CODEXK8S_WORKER_REPLICAS='$(escape_squote "$CODEXK8S_WORKER_REPLICAS")'
CODEXK8S_WORKER_POLL_INTERVAL='$(escape_squote "$CODEXK8S_WORKER_POLL_INTERVAL")'
CODEXK8S_WORKER_CLAIM_LIMIT='$(escape_squote "$CODEXK8S_WORKER_CLAIM_LIMIT")'
CODEXK8S_WORKER_RUNNING_CHECK_LIMIT='$(escape_squote "$CODEXK8S_WORKER_RUNNING_CHECK_LIMIT")'
CODEXK8S_WORKER_SLOTS_PER_PROJECT='$(escape_squote "$CODEXK8S_WORKER_SLOTS_PER_PROJECT")'
CODEXK8S_WORKER_SLOT_LEASE_TTL='$(escape_squote "$CODEXK8S_WORKER_SLOT_LEASE_TTL")'
CODEXK8S_WORKER_K8S_NAMESPACE='$(escape_squote "$CODEXK8S_WORKER_K8S_NAMESPACE")'
CODEXK8S_WORKER_JOB_IMAGE='$(escape_squote "$CODEXK8S_WORKER_JOB_IMAGE")'
CODEXK8S_WORKER_JOB_COMMAND='$(escape_squote "$CODEXK8S_WORKER_JOB_COMMAND")'
CODEXK8S_WORKER_JOB_TTL_SECONDS='$(escape_squote "$CODEXK8S_WORKER_JOB_TTL_SECONDS")'
CODEXK8S_WORKER_JOB_BACKOFF_LIMIT='$(escape_squote "$CODEXK8S_WORKER_JOB_BACKOFF_LIMIT")'
CODEXK8S_WORKER_JOB_ACTIVE_DEADLINE_SECONDS='$(escape_squote "$CODEXK8S_WORKER_JOB_ACTIVE_DEADLINE_SECONDS")'
CODEXK8S_WORKER_RUN_NAMESPACE_PREFIX='$(escape_squote "$CODEXK8S_WORKER_RUN_NAMESPACE_PREFIX")'
CODEXK8S_WORKER_RUN_NAMESPACE_CLEANUP='$(escape_squote "$CODEXK8S_WORKER_RUN_NAMESPACE_CLEANUP")'
CODEXK8S_WORKER_RUN_SERVICE_ACCOUNT='$(escape_squote "$CODEXK8S_WORKER_RUN_SERVICE_ACCOUNT")'
CODEXK8S_WORKER_RUN_ROLE_NAME='$(escape_squote "$CODEXK8S_WORKER_RUN_ROLE_NAME")'
CODEXK8S_WORKER_RUN_ROLE_BINDING_NAME='$(escape_squote "$CODEXK8S_WORKER_RUN_ROLE_BINDING_NAME")'
CODEXK8S_WORKER_RUN_RESOURCE_QUOTA_NAME='$(escape_squote "$CODEXK8S_WORKER_RUN_RESOURCE_QUOTA_NAME")'
CODEXK8S_WORKER_RUN_LIMIT_RANGE_NAME='$(escape_squote "$CODEXK8S_WORKER_RUN_LIMIT_RANGE_NAME")'
CODEXK8S_WORKER_RUN_CREDENTIALS_SECRET_NAME='$(escape_squote "$CODEXK8S_WORKER_RUN_CREDENTIALS_SECRET_NAME")'
CODEXK8S_WORKER_RUN_QUOTA_PODS='$(escape_squote "$CODEXK8S_WORKER_RUN_QUOTA_PODS")'
CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_CPU='$(escape_squote "$CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_CPU")'
CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_MEMORY='$(escape_squote "$CODEXK8S_WORKER_RUN_QUOTA_REQUESTS_MEMORY")'
CODEXK8S_WORKER_RUN_QUOTA_LIMITS_CPU='$(escape_squote "$CODEXK8S_WORKER_RUN_QUOTA_LIMITS_CPU")'
CODEXK8S_WORKER_RUN_QUOTA_LIMITS_MEMORY='$(escape_squote "$CODEXK8S_WORKER_RUN_QUOTA_LIMITS_MEMORY")'
CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_CPU='$(escape_squote "$CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_CPU")'
CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_MEMORY='$(escape_squote "$CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_REQUEST_MEMORY")'
CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_CPU='$(escape_squote "$CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_CPU")'
CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_MEMORY='$(escape_squote "$CODEXK8S_WORKER_RUN_LIMIT_DEFAULT_MEMORY")'
CODEXK8S_AGENT_DEFAULT_MODEL='$(escape_squote "$CODEXK8S_AGENT_DEFAULT_MODEL")'
CODEXK8S_AGENT_DEFAULT_REASONING_EFFORT='$(escape_squote "$CODEXK8S_AGENT_DEFAULT_REASONING_EFFORT")'
CODEXK8S_AGENT_DEFAULT_LOCALE='$(escape_squote "$CODEXK8S_AGENT_DEFAULT_LOCALE")'
CODEXK8S_AGENT_BASE_BRANCH='$(escape_squote "$CODEXK8S_AGENT_BASE_BRANCH")'
CODEXK8S_CONTROL_PLANE_GRPC_TARGET='$(escape_squote "$CODEXK8S_CONTROL_PLANE_GRPC_TARGET")'
CODEXK8S_CONTROL_PLANE_MCP_BASE_URL='$(escape_squote "$CODEXK8S_CONTROL_PLANE_MCP_BASE_URL")'
CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_CPU='$(escape_squote "$CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_CPU")'
CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_MEMORY='$(escape_squote "$CODEXK8S_API_GATEWAY_RESOURCES_REQUEST_MEMORY")'
CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_CPU='$(escape_squote "$CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_CPU")'
CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_MEMORY='$(escape_squote "$CODEXK8S_API_GATEWAY_RESOURCES_LIMIT_MEMORY")'
CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_CPU='$(escape_squote "$CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_CPU")'
CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_MEMORY='$(escape_squote "$CODEXK8S_CONTROL_PLANE_RESOURCES_REQUEST_MEMORY")'
CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_CPU='$(escape_squote "$CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_CPU")'
CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_MEMORY='$(escape_squote "$CODEXK8S_CONTROL_PLANE_RESOURCES_LIMIT_MEMORY")'
CODEXK8S_WORKER_RESOURCES_REQUEST_CPU='$(escape_squote "$CODEXK8S_WORKER_RESOURCES_REQUEST_CPU")'
CODEXK8S_WORKER_RESOURCES_REQUEST_MEMORY='$(escape_squote "$CODEXK8S_WORKER_RESOURCES_REQUEST_MEMORY")'
CODEXK8S_WORKER_RESOURCES_LIMIT_CPU='$(escape_squote "$CODEXK8S_WORKER_RESOURCES_LIMIT_CPU")'
CODEXK8S_WORKER_RESOURCES_LIMIT_MEMORY='$(escape_squote "$CODEXK8S_WORKER_RESOURCES_LIMIT_MEMORY")'
CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_CPU='$(escape_squote "$CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_CPU")'
CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_MEMORY='$(escape_squote "$CODEXK8S_WEB_CONSOLE_RESOURCES_REQUEST_MEMORY")'
CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_CPU='$(escape_squote "$CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_CPU")'
CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_MEMORY='$(escape_squote "$CODEXK8S_WEB_CONSOLE_RESOURCES_LIMIT_MEMORY")'
CODEXK8S_KANIKO_RESOURCES_REQUEST_CPU='$(escape_squote "$CODEXK8S_KANIKO_RESOURCES_REQUEST_CPU")'
CODEXK8S_KANIKO_RESOURCES_REQUEST_MEMORY='$(escape_squote "$CODEXK8S_KANIKO_RESOURCES_REQUEST_MEMORY")'
CODEXK8S_KANIKO_RESOURCES_LIMIT_CPU='$(escape_squote "$CODEXK8S_KANIKO_RESOURCES_LIMIT_CPU")'
CODEXK8S_KANIKO_RESOURCES_LIMIT_MEMORY='$(escape_squote "$CODEXK8S_KANIKO_RESOURCES_LIMIT_MEMORY")'
CODEXK8S_KANIKO_CACHE_ENABLED='$(escape_squote "$CODEXK8S_KANIKO_CACHE_ENABLED")'
CODEXK8S_KANIKO_CACHE_REPO='$(escape_squote "$CODEXK8S_KANIKO_CACHE_REPO")'
CODEXK8S_KANIKO_CACHE_TTL='$(escape_squote "$CODEXK8S_KANIKO_CACHE_TTL")'
CODEXK8S_KANIKO_CACHE_COMPRESSED='$(escape_squote "$CODEXK8S_KANIKO_CACHE_COMPRESSED")'
CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL='$(escape_squote "$CODEXK8S_KANIKO_MATRIX_MAX_PARALLEL")'
CODEXK8S_RUN_DEV_LABEL='$(escape_squote "$CODEXK8S_RUN_DEV_LABEL")'
CODEXK8S_RUN_DEV_REVISE_LABEL='$(escape_squote "$CODEXK8S_RUN_DEV_REVISE_LABEL")'
CODEXK8S_RUN_DEBUG_LABEL='$(escape_squote "$CODEXK8S_RUN_DEBUG_LABEL")'
CODEXK8S_INGRESS_HOST_NETWORK='$(escape_squote "$CODEXK8S_INGRESS_HOST_NETWORK")'
CODEXK8S_FIREWALL_ENABLED='$(escape_squote "$CODEXK8S_FIREWALL_ENABLED")'
CODEXK8S_SSH_PORT='$(escape_squote "$CODEXK8S_SSH_PORT")'
CODEXK8S_NETWORK_POLICY_BASELINE='$(escape_squote "$CODEXK8S_NETWORK_POLICY_BASELINE")'
CODEXK8S_PLATFORM_MCP_PORT='$(escape_squote "$CODEXK8S_PLATFORM_MCP_PORT")'
CODEXK8S_K8S_API_CIDR='$(escape_squote "$CODEXK8S_K8S_API_CIDR")'
CODEXK8S_K8S_API_PORT='$(escape_squote "$CODEXK8S_K8S_API_PORT")'
CODEXK8S_DNS_WAIT_TIMEOUT='$(escape_squote "$CODEXK8S_DNS_WAIT_TIMEOUT")'
CODEXK8S_DNS_WAIT_INTERVAL='$(escape_squote "$CODEXK8S_DNS_WAIT_INTERVAL")'
CODEXK8S_NODE_DISCOVERY_TIMEOUT='$(escape_squote "$CODEXK8S_NODE_DISCOVERY_TIMEOUT")'
CODEXK8S_NODE_READY_TIMEOUT='$(escape_squote "$CODEXK8S_NODE_READY_TIMEOUT")'
CODEXK8S_INGRESS_READY_TIMEOUT='$(escape_squote "$CODEXK8S_INGRESS_READY_TIMEOUT")'
CODEXK8S_CERT_MANAGER_READY_TIMEOUT='$(escape_squote "$CODEXK8S_CERT_MANAGER_READY_TIMEOUT")'
CODEXK8S_HELM_TIMEOUT='$(escape_squote "$CODEXK8S_HELM_TIMEOUT")'
CODEXK8S_ROLLOUT_TIMEOUT='$(escape_squote "$CODEXK8S_ROLLOUT_TIMEOUT")'
CODEXK8S_WAIT_ROLLOUT='$(escape_squote "$CODEXK8S_WAIT_ROLLOUT")'
CODEXK8S_KANIKO_TIMEOUT='$(escape_squote "$CODEXK8S_KANIKO_TIMEOUT")'
CODEXK8S_LEARNING_MODE_DEFAULT='$(escape_squote "$CODEXK8S_LEARNING_MODE_DEFAULT")'
CODEXK8S_POSTGRES_DB='$(escape_squote "$CODEXK8S_POSTGRES_DB")'
CODEXK8S_POSTGRES_USER='$(escape_squote "$CODEXK8S_POSTGRES_USER")'
CODEXK8S_POSTGRES_PASSWORD='$(escape_squote "$CODEXK8S_POSTGRES_PASSWORD")'
CODEXK8S_PROJECT_DB_ADMIN_HOST='$(escape_squote "$CODEXK8S_PROJECT_DB_ADMIN_HOST")'
CODEXK8S_PROJECT_DB_ADMIN_PORT='$(escape_squote "$CODEXK8S_PROJECT_DB_ADMIN_PORT")'
CODEXK8S_PROJECT_DB_ADMIN_USER='$(escape_squote "$CODEXK8S_PROJECT_DB_ADMIN_USER")'
CODEXK8S_PROJECT_DB_ADMIN_PASSWORD='$(escape_squote "$CODEXK8S_PROJECT_DB_ADMIN_PASSWORD")'
CODEXK8S_PROJECT_DB_ADMIN_SSLMODE='$(escape_squote "$CODEXK8S_PROJECT_DB_ADMIN_SSLMODE")'
CODEXK8S_PROJECT_DB_ADMIN_DATABASE='$(escape_squote "$CODEXK8S_PROJECT_DB_ADMIN_DATABASE")'
CODEXK8S_APP_SECRET_KEY='$(escape_squote "$CODEXK8S_APP_SECRET_KEY")'
CODEXK8S_TOKEN_ENCRYPTION_KEY='$(escape_squote "$CODEXK8S_TOKEN_ENCRYPTION_KEY")'
CODEXK8S_GITHUB_WEBHOOK_SECRET='$(escape_squote "$CODEXK8S_GITHUB_WEBHOOK_SECRET")'
ENV

log "Copy remote bootstrap scripts to ${TARGET_ROOT_USER}@${TARGET_HOST}:${REMOTE_DIR}"
ssh -i "$TARGET_ROOT_SSH_KEY" -p "$TARGET_PORT" "${TARGET_ROOT_USER}@${TARGET_HOST}" "mkdir -p '${REMOTE_DIR}'"
scp -i "$TARGET_ROOT_SSH_KEY" -P "$TARGET_PORT" -r "${ROOT_DIR}/remote" "${TARGET_ROOT_USER}@${TARGET_HOST}:${REMOTE_DIR}/"
scp -i "$TARGET_ROOT_SSH_KEY" -P "$TARGET_PORT" "${TMP_DIR}/bootstrap.env" "${TARGET_ROOT_USER}@${TARGET_HOST}:${REMOTE_ENV}"

log "Run remote bootstrap"
ssh -i "$TARGET_ROOT_SSH_KEY" -p "$TARGET_PORT" "${TARGET_ROOT_USER}@${TARGET_HOST}" \
  "bash '${REMOTE_DIR}/remote/bootstrap_staging.sh' '${REMOTE_ENV}'"

log "Bootstrap completed"
log "Next: push to main should trigger staging deploy workflow once runner is online"
